// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// specs/providers/daytona.yaml
// Request helpers map shared fields into the native SDK and return anything
// left unmapped. Response helpers copy reported metadata without inventing
// omitted values.
//
// Example:
//
//	native, remaining, err := mapResources(request.Resources)
package daytona

import (
	daytona "github.com/daytona/clients/sdk-go/pkg/daytona"
	types "github.com/daytona/clients/sdk-go/pkg/types"
	sandbox "github.com/sandbox-kit/kit/sdks/go/sandbox"
	math "math"
	time "time"
)

// mapLifetimePolicies maps supplied fields for mapLifetimePolicies into the
// native request and returns the fields that were not mapped.
func mapLifetimePolicies(source *sandbox.LifetimePolicy) (types.SandboxBaseParams, sandbox.LifetimePolicy, error) {
	target := types.SandboxBaseParams{}
	remaining := sandbox.LifetimePolicy{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	if policy := source.IdleStop; policy != nil {
		switch policy.Mode {
		case sandbox.PolicyModeDefault:
		case sandbox.PolicyModeDisabled:
			target.AutoStopInterval = sandbox.Value(0)
		case sandbox.PolicyModeAfter:
			if policy.After == nil {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdleStop, Message: "sandbox-kit daytona: idle_stop: duration is required"}, nil)
			}
			if *policy.After == 0 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindUnsupported, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdleStop, Message: "sandbox-kit daytona: idle_stop: immediate action is not representable"}, nil)
			}
			duration := *policy.After
			if duration < 0 || duration%time.Minute != 0 || duration/time.Minute > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdleStop, Message: "sandbox-kit daytona: idle_stop: delay cannot be represented in whole minutes"}, nil)
			}
			value := int(duration / time.Minute)
			target.AutoStopInterval = &value
		default:
			return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdleStop, Message: "sandbox-kit daytona: idle_stop: unknown policy mode"}, nil)
		}
	}
	remaining.IdleStop = nil
	if policy := source.IdlePause; policy != nil {
		switch policy.Mode {
		case sandbox.PolicyModeDefault:
		case sandbox.PolicyModeDisabled:
			target.AutoPauseInterval = sandbox.Value(0)
		case sandbox.PolicyModeAfter:
			if policy.After == nil {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdlePause, Message: "sandbox-kit daytona: idle_pause: duration is required"}, nil)
			}
			if *policy.After == 0 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindUnsupported, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdlePause, Message: "sandbox-kit daytona: idle_pause: immediate action is not representable"}, nil)
			}
			duration := *policy.After
			if duration < 0 || duration%time.Minute != 0 || duration/time.Minute > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdlePause, Message: "sandbox-kit daytona: idle_pause: delay cannot be represented in whole minutes"}, nil)
			}
			value := int(duration / time.Minute)
			target.AutoPauseInterval = &value
		default:
			return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeIdlePause, Message: "sandbox-kit daytona: idle_pause: unknown policy mode"}, nil)
		}
	}
	remaining.IdlePause = nil
	if policy := source.StoppedArchive; policy != nil {
		switch policy.Mode {
		case sandbox.PolicyModeDefault:
		case sandbox.PolicyModeDisabled:
			return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindUnsupported, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedArchive, Message: "sandbox-kit daytona: stopped_archive: explicit disabling is not representable; native zero has a different meaning"}, nil)
		case sandbox.PolicyModeAfter:
			if policy.After == nil {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedArchive, Message: "sandbox-kit daytona: stopped_archive: duration is required"}, nil)
			}
			if *policy.After == 0 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindUnsupported, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedArchive, Message: "sandbox-kit daytona: stopped_archive: immediate action is not representable"}, nil)
			}
			duration := *policy.After
			if duration < 0 || duration%time.Minute != 0 || duration/time.Minute > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedArchive, Message: "sandbox-kit daytona: stopped_archive: delay cannot be represented in whole minutes"}, nil)
			}
			if duration/time.Minute > 43200 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedArchive, Message: "sandbox-kit daytona: stopped_archive: delay exceeds documented maximum"}, nil)
			}
			value := int(duration / time.Minute)
			target.AutoArchiveInterval = &value
		default:
			return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedArchive, Message: "sandbox-kit daytona: stopped_archive: unknown policy mode"}, nil)
		}
	}
	remaining.StoppedArchive = nil
	if policy := source.StoppedDelete; policy != nil {
		switch policy.Mode {
		case sandbox.PolicyModeDefault:
		case sandbox.PolicyModeDisabled:
			return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindUnsupported, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedDelete, Message: "sandbox-kit daytona: stopped_delete: explicit disabling is not representable; native zero has a different meaning"}, nil)
		case sandbox.PolicyModeAfter:
			if policy.After == nil {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedDelete, Message: "sandbox-kit daytona: stopped_delete: duration is required"}, nil)
			}
			duration := *policy.After
			if duration < 0 || duration%time.Minute != 0 || duration/time.Minute > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedDelete, Message: "sandbox-kit daytona: stopped_delete: delay cannot be represented in whole minutes"}, nil)
			}
			value := int(duration / time.Minute)
			target.AutoDeleteInterval = &value
		default:
			return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetimeStoppedDelete, Message: "sandbox-kit daytona: stopped_delete: unknown policy mode"}, nil)
		}
	}
	remaining.StoppedDelete = nil
	return target, remaining, nil
}

// mapCommonCreateFields maps supplied fields for mapCommonCreateFields into
// the native request and returns the fields that were not mapped.
func mapCommonCreateFields(source *sandbox.CreateOptions) (types.SandboxBaseParams, sandbox.CreateOptions, error) {
	target := types.SandboxBaseParams{}
	remaining := sandbox.CreateOptions{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	if source.Name != nil {
		{
			value := source.GetName()
			target.Name = value
		}
	}
	remaining.Name = nil
	{
		value := source.Environment
		target.EnvVars = value
	}
	remaining.Environment = nil
	{
		value := source.Labels
		target.Labels = value
	}
	remaining.Labels = nil
	return target, remaining, nil
}

// mapResources maps supplied fields for mapResources into the native request
// and returns the fields that were not mapped.
func mapResources(source *sandbox.Resources) (types.Resources, sandbox.Resources, error) {
	target := types.Resources{}
	remaining := sandbox.Resources{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	if source.CPUCores != nil {
		{
			value := source.GetCPUCores()
			if float64(value) != math.Trunc(float64(value)) || value > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldResourcesCPUCores, Message: "sandbox-kit daytona: cpu_cores cannot be represented"}, nil)
			}
			target.CPU = int(value)
		}
	}
	remaining.CPUCores = nil
	if source.MemoryMiB != nil {
		{
			value := source.GetMemoryMiB()
			if value%1024 != 0 || value/1024 > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldResourcesMemoryMiB, Message: "sandbox-kit daytona: memory_mib cannot be represented"}, nil)
			}
			target.Memory = int(value / 1024)
		}
	}
	remaining.MemoryMiB = nil
	if source.DiskMiB != nil {
		{
			value := source.GetDiskMiB()
			if value%1024 != 0 || value/1024 > 2147483647 {
				return target, remaining, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldResourcesDiskMiB, Message: "sandbox-kit daytona: disk_mib cannot be represented"}, nil)
			}
			target.Disk = int(value / 1024)
		}
	}
	remaining.DiskMiB = nil
	return target, remaining, nil
}

// mapSandboxInfo maps native fields for mapSandboxInfo into shared metadata.
// It does not invent values the SDK omitted.
func mapSandboxInfo(source *daytona.Sandbox) (sandbox.SandboxInfo, error) {
	target := sandbox.SandboxInfo{}
	if source == nil {
		return target, nil
	}
	target.Origins = map[string]sandbox.ValueOrigin{}
	{
		value := source.ID
		target.ID = value
		target.Origins["id"] = sandbox.ValueOriginProvider
	}
	{
		value := source.Name
		target.Name = sandbox.Value(value)
		if target.Name != nil {
			target.Origins["name"] = sandbox.ValueOriginProvider
		}
	}
	{
		value := source.State
		target.ProviderState = sandbox.Value(string(value))
		if target.ProviderState != nil {
			target.Origins["provider_state"] = sandbox.ValueOriginProvider
		}
	}
	{
		value := source.Target
		target.Region = sandbox.Value(value)
		if target.Region != nil {
			target.Origins["region"] = sandbox.ValueOriginProvider
		}
	}
	{
		value := source.Labels
		target.Labels = value
		if target.Labels != nil {
			target.Origins["labels"] = sandbox.ValueOriginProvider
		}
	}
	target.Provider = "daytona"
	return target, nil
}

// mapAllocatedResources maps native fields for mapAllocatedResources into
// shared metadata. It does not invent values the SDK omitted.
func mapAllocatedResources(source *daytona.Sandbox) (sandbox.Resources, error) {
	target := sandbox.Resources{}
	if source == nil {
		return target, nil
	}
	if !(source.Cpu > 0 && source.Memory > 0 && source.Disk > 0) {
		return target, nil
	}
	{
		value := source.Cpu
		target.CPUCores = sandbox.Value(float64(value))
	}
	{
		value := source.Memory
		if value < 0 || uint64(value) > ^uint64(0)/1024 {
			return target, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidResponse, Provider: "daytona", Operation: "create", Field: "memory", Message: "sandbox-kit daytona: memory cannot be represented"}, nil)
		}
		target.MemoryMiB = sandbox.Value(uint64(value) * 1024)
	}
	{
		value := source.Disk
		if value < 0 || uint64(value) > ^uint64(0)/1024 {
			return target, sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidResponse, Provider: "daytona", Operation: "create", Field: "disk", Message: "sandbox-kit daytona: disk cannot be represented"}, nil)
		}
		target.DiskMiB = sandbox.Value(uint64(value) * 1024)
	}
	return target, nil
}

// mapClientSettings maps supplied fields for mapClientSettings into the native
// request and returns the fields that were not mapped.
func mapClientSettings(source *sandbox.Config) (types.DaytonaConfig, sandbox.Config, error) {
	target := types.DaytonaConfig{}
	remaining := sandbox.Config{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	if source.Endpoint != nil {
		{
			value := source.GetEndpoint()
			target.APIUrl = value
		}
	}
	remaining.Endpoint = nil
	if source.Region != nil {
		{
			value := source.GetRegion()
			target.Target = value
		}
	}
	remaining.Region = nil
	return target, remaining, nil
}

// mapAPIKeyCredentials maps supplied fields for mapAPIKeyCredentials into the
// native request and returns the fields that were not mapped.
func mapAPIKeyCredentials(source *sandbox.APIKeyCredentials) (types.DaytonaConfig, sandbox.APIKeyCredentials, error) {
	target := types.DaytonaConfig{}
	remaining := sandbox.APIKeyCredentials{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	{
		value := source.Key
		target.APIKey = value
	}
	remaining.Key = ""
	return target, remaining, nil
}

// mapBearerAuth maps supplied fields for mapBearerAuth into the native request
// and returns the fields that were not mapped.
func mapBearerAuth(source *sandbox.BearerTokenCredentials) (types.DaytonaConfig, sandbox.BearerTokenCredentials, error) {
	target := types.DaytonaConfig{}
	remaining := sandbox.BearerTokenCredentials{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	{
		value := source.Token
		target.JWTToken = value
	}
	remaining.Token = ""
	return target, remaining, nil
}

// mapScope maps supplied fields for mapScope into the native request and
// returns the fields that were not mapped.
func mapScope(source *sandbox.Scope) (types.DaytonaConfig, sandbox.Scope, error) {
	target := types.DaytonaConfig{}
	remaining := sandbox.Scope{}
	if source != nil {
		remaining = *source
	}
	if source == nil {
		return target, remaining, nil
	}
	if source.OrganizationID != nil {
		{
			value := source.GetOrganizationID()
			target.OrganizationID = value
		}
	}
	remaining.OrganizationID = nil
	return target, remaining, nil
}
