// Code generated by protoc-gen-kit-go. DO NOT EDIT.
package daytona

import (
	fmt "fmt"
	types "github.com/daytona/clients/sdk-go/pkg/types"
	sandbox "github.com/sandbox-kit/kit/sdks/go/sandbox"
)

func mapClientConfig(config *sandbox.Config) (types.DaytonaConfig, error) {
	var params types.DaytonaConfig
	if config == nil {
		config = &sandbox.Config{}
	}
	if err := sandbox.ValidateConfig(config); err != nil {
		return params, err
	}
	params, remaining, err := mapClientSettings(config)
	if err != nil {
		return params, err
	}
	remaining.Provider = nil
	remaining.Timeout = nil
	remaining.Auth = nil
	remaining.Scope = nil
	if config.Scope != nil {
		mapped, rest, err := mapScope(config.Scope)
		if err != nil {
			return params, err
		}
		if err := sandbox.RejectUnmapped("daytona client scope", &rest); err != nil {
			return params, err
		}
		params.OrganizationID = mapped.OrganizationID
	}
	if auth := config.GetAuth(); auth != nil {
		switch {
		case auth.APIKey != nil:
			mapped, rest, err := mapAPIKeyCredentials(auth.APIKey)
			if err != nil {
				return params, err
			}
			if err := sandbox.RejectUnmapped("daytona client api_key", &rest); err != nil {
				return params, err
			}
			params.APIKey = mapped.APIKey
		case auth.BearerToken != nil:
			mapped, rest, err := mapBearerAuth(auth.BearerToken)
			if err != nil {
				return params, err
			}
			if err := sandbox.RejectUnmapped("daytona client bearer_token", &rest); err != nil {
				return params, err
			}
			params.JWTToken = mapped.JWTToken
		default:
			return params, fmt.Errorf("sandbox-kit daytona: unsupported authentication mode")
		}
	}
	if err := sandbox.RejectUnmapped("daytona client", &remaining); err != nil {
		return params, err
	}
	return params, nil
}
