// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/providers/daytona/v1/provider.proto
package daytona

import (
	context "context"
	daytona "github.com/daytona/clients/sdk-go/pkg/daytona"
	sandbox "github.com/sandbox-kit/kit/sdks/go/sandbox"
)

// Provider initializes the provider SDK from sandbox.Config.
type Provider struct{}

// New selects this provider; SDK initialization happens in sandbox.NewClient.
func New() *Provider           { return &Provider{} }
func (*Provider) Name() string { return "daytona" }
func (*Provider) NewClient(config *sandbox.Config) (sandbox.Backend, error) {
	return newBackend(config)
}

// backend owns its initialized SDK; it is returned by the factory.
type backend struct {
	client *daytona.Client
}

func newBackend(config *sandbox.Config) (sandbox.Backend, error) {
	if config == nil {
		config = &sandbox.Config{}
	}
	params, err := mapClientConfig(config)
	if err != nil {
		return nil, err
	}
	native, err := daytona.NewClientWithConfig(&params)
	if err != nil {
		return nil, err
	}
	result := &backend{client: native}
	captureBackendState(result, config)
	return result, nil
}
func captureBackendState(result *backend, config *sandbox.Config) {
	if config == nil {
		return
	}
}
func (*backend) Name() string { return "daytona" }
func (a *backend) Create(ctx context.Context, request *sandbox.CreateOptions) (*sandbox.CreateResult, error) {
	return a.create(ctx, request)
}
func (a *backend) Close(ctx context.Context) error {
	return a.client.Close(ctx)
}

var _ sandbox.Provider = (*Provider)(nil)
var _ sandbox.Backend = (*backend)(nil)
