// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// Provider checks reject creation settings this integration cannot honor. They
// run before the native create call.
//
// Example:
//
//	if err := validateProviderCreate(request); err != nil { return nil, err }
package daytona

import (
	sandbox "github.com/sandbox-kit/kit/sdks/go/sandbox"
	netip "net/netip"
	url "net/url"
	regexp "regexp"
	strings "strings"
)

var providerEnvNamePattern = regexp.MustCompile("^[A-Za-z_][A-Za-z0-9_]*$")
var providerDomainPattern = regexp.MustCompile("(?i)^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)*[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.?$")

// validateProviderCreate rejects creation settings this provider cannot honor.
// It runs before the native create call.
func validateProviderCreate(request *sandbox.CreateOptions) error {
	if request == nil {
		return nil
	}
	if request.Runtime != nil {
		if request.Runtime.Language != nil {
			if *request.Runtime.Language != "python" && *request.Runtime.Language != "javascript" && *request.Runtime.Language != "typescript" {
				return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindUnsupported, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldRuntimeLanguage, Message: "sandbox-kit daytona: runtime.language is outside supported values"}, nil)
			}
		}
	}
	if request.Network != nil {
		if request.Network.OutboundProxyURL != nil {
			parsed, err := url.Parse(*request.Network.OutboundProxyURL)
			if err != nil || parsed.Host == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") {
				return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldNetworkOutboundProxyURL, Message: "sandbox-kit daytona: network.outbound_proxy_url is outside supported values"}, nil)
			}
		}
	}
	if request.Network != nil {
		if request.Network.OutboundCIDRs != nil {
			for _, value := range request.Network.OutboundCIDRs.Entries {
				_, err := netip.ParsePrefix(value)
				if err != nil {
					return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldNetworkOutboundCIDRsEntries, Message: "sandbox-kit daytona: network.outbound_cidrs.entries is outside supported values"}, nil)
				}
			}
		}
	}
	if request.Network != nil {
		if request.Network.OutboundDomains != nil {
			for _, value := range request.Network.OutboundDomains.Entries {
				domain := strings.TrimPrefix(value, "*.")
				matched := providerDomainPattern.MatchString(domain)
				if !matched || len(domain) > 253 {
					return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldNetworkOutboundDomainsEntries, Message: "sandbox-kit daytona: network.outbound_domains.entries is outside supported values"}, nil)
				}
			}
		}
	}
	if request.Security != nil {
		for _, item := range request.Security.Secrets {
			if item == nil {
				return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldSecuritySecretsEnvironmentVariable, Message: "sandbox-kit: nil configuration entry"}, nil)
			}
			if item.EnvironmentVariable != nil {
				matched := providerEnvNamePattern.MatchString(*item.EnvironmentVariable)
				if !matched {
					return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldSecuritySecretsEnvironmentVariable, Message: "sandbox-kit daytona: security.secrets.environment_variable is outside supported values"}, nil)
				}
			}
		}
	}
	if lifetime := request.Lifetime; lifetime != nil {
		if (lifetime.IdleStop != nil && lifetime.IdleStop.Mode == 2 && lifetime.IdleStop.After != nil && *lifetime.IdleStop.After > 0) && (lifetime.IdlePause != nil && lifetime.IdlePause.Mode == 2 && lifetime.IdlePause.After != nil && *lifetime.IdlePause.After > 0) {
			return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetime, Message: "sandbox-kit: incompatible lifetime policies"}, nil)
		}
	}
	if lifetime := request.Lifetime; lifetime != nil {
		if (lifetime.IdlePause != nil && lifetime.IdlePause.Mode == 2 && lifetime.IdlePause.After != nil && *lifetime.IdlePause.After > 0) && (lifetime.GetEphemeral()) {
			return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetime, Message: "sandbox-kit: incompatible lifetime policies"}, nil)
		}
	}
	if lifetime := request.Lifetime; lifetime != nil {
		if (lifetime.IdlePause != nil && lifetime.IdlePause.Mode == 2 && lifetime.IdlePause.After != nil && *lifetime.IdlePause.After > 0) && (lifetime.StoppedDelete != nil && lifetime.StoppedDelete.Mode == 2 && lifetime.StoppedDelete.After != nil && *lifetime.StoppedDelete.After == 0) {
			return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetime, Message: "sandbox-kit: incompatible lifetime policies"}, nil)
		}
	}
	if lifetime := request.Lifetime; lifetime != nil {
		if (lifetime.StoppedDelete != nil && lifetime.StoppedDelete.Mode == 2 && lifetime.StoppedDelete.After != nil && *lifetime.StoppedDelete.After > 0) && (lifetime.GetEphemeral()) {
			return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetime, Message: "sandbox-kit: incompatible lifetime policies"}, nil)
		}
	}
	if lifetime := request.Lifetime; lifetime != nil {
		if (lifetime.StoppedArchive != nil && lifetime.StoppedArchive.Mode == 2 && lifetime.StoppedArchive.After != nil && *lifetime.StoppedArchive.After > 0) && (lifetime.GetEphemeral()) {
			return sandbox.NewError(sandbox.ErrorInfo{Kind: sandbox.ErrorKindInvalidArgument, Provider: "daytona", Operation: "create", Field: sandbox.CreateFieldLifetime, Message: "sandbox-kit: incompatible lifetime policies"}, nil)
		}
	}
	return nil
}
