// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/core/v1/client.proto

package core

import (
	"errors"
	"reflect"
)

// Provider identifies an explicitly selected sandbox adapter.
// Future operations map shared requests and responses through the adapter.
type Provider interface{ ProviderName() string }

// Client presents a shared API over an explicitly selected provider.
// Construct it with NewClient; its zero value is not ready for use.
// It owns no connections and performs no authentication or network calls.
type Client struct{ provider Provider }

// NewClient attaches an existing provider without changing its configuration.
// The caller remains responsible for the provider and SDK client's lifetime.
// Constructor errors describe local misuse, not upstream provider failures.
func NewClient(provider Provider) (*Client, error) {
	value := reflect.ValueOf(provider)
	if !value.IsValid() {
		return nil, errors.New("sandbox-kit: provider is required")
	}
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		if value.IsNil() {
			return nil, errors.New("sandbox-kit: provider is required")
		}
	}
	return &Client{provider: provider}, nil
}

// ProviderName identifies the selected provider through the common API.
func (c *Client) ProviderName() string { return c.provider.ProviderName() }
