package clientgen

import (
	"fmt"
	"go/token"
	"unicode"
	"unicode/utf8"

	codegenv1 "github.com/sandbox-kit/kit/tooling/internal/gen/codegen/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

// Generate emits client boilerplate for files declaring a local client.
func Generate(plugin *protogen.Plugin, file *protogen.File) error {
	options := file.Desc.Options()
	if !proto.HasExtension(options, codegenv1.E_Client) {
		return nil
	}
	declaration := proto.GetExtension(options, codegenv1.E_Client).(*codegenv1.ClientDeclaration)
	name := declaration.GetGoName()
	provider := declaration.GetGoProviderInterface()
	for _, ident := range []string{name, provider} {
		first, _ := utf8.DecodeRuneInString(ident)
		if !token.IsIdentifier(ident) || !unicode.IsUpper(first) {
			return fmt.Errorf("%s: client names must be exported Go identifiers: %q", file.Desc.Path(), ident)
		}
	}
	if name == provider || "New"+name == provider {
		return fmt.Errorf("%s: client and provider declaration names collide", file.Desc.Path())
	}

	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".kit.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (\"errors\"; \"reflect\")")
	g.P()
	g.P("// ", provider, " identifies an explicitly selected sandbox adapter.")
	g.P("// Future operations map shared requests and responses through the adapter.")
	g.P("type ", provider, " interface { ProviderName() string }")
	g.P()
	g.P("// ", name, " presents a shared API over an explicitly selected provider.")
	g.P("// Construct it with New", name, "; its zero value is not ready for use.")
	g.P("// It owns no connections and performs no authentication or network calls.")
	g.P("type ", name, " struct { provider ", provider, " }")
	g.P()
	g.P("// New", name, " attaches an existing provider without changing its configuration.")
	g.P("// The caller remains responsible for the provider and SDK client's lifetime.")
	g.P("// Constructor errors describe local misuse, not upstream provider failures.")
	g.P("func New", name, "(provider ", provider, ") (*", name, ", error) {")
	g.P("value := reflect.ValueOf(provider)")
	g.P("if !value.IsValid() { return nil, errors.New(\"sandbox-kit: provider is required\") }")
	g.P("switch value.Kind() {")
	g.P("case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:")
	g.P("if value.IsNil() { return nil, errors.New(\"sandbox-kit: provider is required\") }")
	g.P("}")
	g.P("return &", name, "{provider: provider}, nil")
	g.P("}")
	g.P()
	g.P("// ProviderName identifies the selected provider through the common API.")
	g.P("func (c *", name, ") ProviderName() string { return c.provider.ProviderName() }")
	return nil
}
