package providergen

import (
	"fmt"
	"sort"
	"strconv"

	"github.com/sandbox-kit/kit/tooling/internal/go/naming"
	"github.com/sandbox-kit/kit/tooling/internal/spec"
	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateConfig composes typed mapping groups without embedding Go code in specs.
func GenerateConfig(plugin *protogen.Plugin, file *protogen.File, provider spec.Provider) error {
	c := provider.Client
	if c == nil {
		return nil
	}
	if err := validateComposition(plugin, provider); err != nil {
		return err
	}
	binding := c.Target.Bindings["go"]
	if binding.Import == "" || binding.Name == "" {
		return fmt.Errorf("client target requires Go binding")
	}
	core := protogen.GoImportPath("github.com/sandbox-kit/kit/sdks/go/sandbox")
	ident := func(name string) protogen.GoIdent { return protogen.GoIdent{GoName: name, GoImportPath: core} }
	// Resolve schema names through the same naming emitter as public Go types.
	fieldName := func(message, name string) (string, error) {
		if message == "Config" && name == "provider" {
			return "Provider", nil
		}
		field, err := sharedField(plugin, message, name)
		if err != nil {
			return "", err
		}
		return naming.FieldName(field), nil
	}
	group := func(name string) (spec.Group, error) {
		for _, g := range provider.Groups {
			if g.Name == name && g.Direction == "request" {
				return g, nil
			}
		}
		return spec.Group{}, fmt.Errorf("unknown request mapping group %q", name)
	}
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".client.gen.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P("func mapClientConfig(config *", ident("Config"), ")(", protogen.GoIdent{GoName: binding.Name, GoImportPath: protogen.GoImportPath(binding.Import)}, ",error){")
	g.P("var params ", protogen.GoIdent{GoName: binding.Name, GoImportPath: protogen.GoImportPath(binding.Import)})
	g.P("if config==nil {config=&", ident("Config"), "{}}")
	g.P("if err:=", ident("ValidateConfig"), "(config);err!=nil{return params,err}")
	keys := make([]string, 0, len(c.Rejected))
	for key := range c.Rejected {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		field, err := fieldName("Config", key)
		if err != nil {
			return err
		}
		g.P("if config.", field, "!=nil{return params,", protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}, "(", strconv.Quote("sandbox-kit "+provider.Provider+": "+c.Rejected[key]), ")}")
	}
	if c.Settings != "" {
		grp, err := group(c.Settings)
		if err != nil {
			return err
		}
		if !sameNative(grp.Target, c.Target) {
			return fmt.Errorf("settings mapping has incompatible types")
		}
		g.P("params,remaining,err:=", c.Settings, "(config);if err!=nil{return params,err}")
	} else {
		g.P("remaining:=*config")
	}
	owned := append(append([]string{}, c.Managed...), c.Retained...)
	owned = append(owned, "auth")
	if c.Scope != nil {
		owned = append(owned, "scope")
	}
	for _, key := range owned {
		field, err := fieldName("Config", key)
		if err != nil {
			return err
		}
		g.P("remaining.", field, "=nil")
	}
	for _, key := range keys {
		field, _ := fieldName("Config", key)
		g.P("remaining.", field, "=nil")
	}
	emitComponent := func(component spec.ClientComponent, parent string, message string) error {
		field, err := fieldName(message, component.Field)
		if err != nil {
			return err
		}
		grp, err := group(component.Group)
		if err != nil {
			return err
		}
		g.P("mapped,rest,err:=", component.Group, "(", parent, ".", field, ");if err!=nil{return params,err}")
		for _, key := range component.Retained {
			n, err := fieldName(grp.Source.Name, key)
			if err != nil {
				return err
			}
			g.P("rest.", n, "=nil")
		}
		g.P("if err:=", ident("RejectUnmapped"), "(", strconv.Quote(provider.Provider+" client "+component.Field), ",&rest);err!=nil{return params,err}")
		if component.Destination != "" {
			dest, ok := binding.Fields[component.Destination]
			if !ok {
				return fmt.Errorf("missing destination binding %q", component.Destination)
			}
			g.P("params.", dest, "=&mapped")
		} else {
			if !sameNative(grp.Target, c.Target) {
				return fmt.Errorf("component target type mismatch")
			}
			for _, mapping := range grp.Fields {
				member, ok := grp.Target.Bindings["go"].Fields[mapping.To]
				if !ok {
					return fmt.Errorf("missing component member binding")
				}
				g.P("params.", member, "=mapped.", member)
			}
		}
		return nil
	}
	if c.Scope != nil {
		if c.Scope.Field != "scope" {
			return fmt.Errorf("client scope must select scope")
		}
		g.P("if config.Scope!=nil{")
		if err := emitComponent(*c.Scope, "config", "Config"); err != nil {
			return err
		}
		g.P("}")
	}
	g.P("if auth:=config.GetAuth();auth!=nil{switch{")
	seen := map[string]bool{}
	for _, component := range c.Auth {
		if seen[component.Field] {
			return fmt.Errorf("duplicate auth variant %q", component.Field)
		}
		seen[component.Field] = true
		field, err := fieldName("AuthConfig", component.Field)
		if err != nil {
			return err
		}
		g.P("case auth.", field, "!=nil:")
		if err := emitComponent(component, "auth", "AuthConfig"); err != nil {
			return err
		}
	}
	g.P("default:return params,", protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}, "(", strconv.Quote("sandbox-kit "+provider.Provider+": unsupported authentication mode"), ")}}")
	g.P("if err:=", ident("RejectUnmapped"), "(", strconv.Quote(provider.Provider+" client"), ",&remaining);err!=nil{return params,err};return params,nil}")
	return nil
}
