package providergen

import (
	"fmt"
	"go/token"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	codegen "github.com/sandbox-kit/kit/tooling/internal/gen/codegen/v1"
	rules "github.com/sandbox-kit/kit/tooling/internal/spec"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

// Generate emits a typed provider and private SDK backend; YAML mappings are emitted separately.
func Generate(plugin *protogen.Plugin, file *protogen.File, runtime rules.RuntimeBinding) error {
	if !proto.HasExtension(file.Desc.Options(), codegen.E_Provider) {
		return nil
	}
	if proto.HasExtension(file.Desc.Options(), codegen.E_Client) {
		return fmt.Errorf("%s: declare client and provider separately", file.Desc.Path())
	}
	spec := proto.GetExtension(file.Desc.Options(), codegen.E_Provider).(*codegen.ProviderDeclaration)
	name := spec.GetName()
	publicName := name
	sdk := spec.GetSdks()["go"]
	first, _ := utf8.DecodeRuneInString(name)
	if !token.IsIdentifier(name) || !unicode.IsUpper(first) || name == "New" {
		return fmt.Errorf("%s: invalid backend name %q", file.Desc.Path(), name)
	}
	if strings.TrimSpace(spec.GetProviderName()) == "" || sdk == nil || sdk.GetImportPath() == "" || !token.IsIdentifier(sdk.GetClientType()) {
		return fmt.Errorf("%s: provider and Go SDK binding are required", file.Desc.Path())
	}
	name = strings.ToLower(publicName[:1]) + publicName[1:]
	client := protogen.GoIdent{GoName: sdk.GetClientType(), GoImportPath: protogen.GoImportPath(sdk.GetImportPath())}
	sandboxPath := protogen.GoImportPath("github.com/sandbox-kit/kit/sdks/go/sandbox")
	request := protogen.GoIdent{GoName: "CreateOptions", GoImportPath: sandboxPath}
	response := protogen.GoIdent{GoName: "CreateResult", GoImportPath: sandboxPath}
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".gen.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("package ", file.GoPackageName)
	g.P("// Provider initializes the provider SDK from sandbox.Config.")
	g.P("type Provider struct{}")
	g.P("// New selects this provider; SDK initialization happens in sandbox.NewClient.")
	g.P("func New()*Provider{return &Provider{}}")
	g.P("func(*Provider)Name()string{return ", strconv.Quote(spec.GetProviderName()), "}")
	g.P("func(*Provider)NewClient(config *", protogen.GoIdent{GoName: "Config", GoImportPath: sandboxPath}, ")(", protogen.GoIdent{GoName: "Backend", GoImportPath: sandboxPath}, ",error){return newBackend(config)}")
	g.P("// ", name, " owns its initialized SDK; it is returned by the factory.")
	g.P("type ", name, " struct{client *", client)
	seen := map[string]bool{"client": true}
	for _, field := range runtime.State {
		if !token.IsIdentifier(field.Name) || seen[field.Name] {
			return fmt.Errorf("invalid or duplicate backend state field %q", field.Name)
		}
		seen[field.Name] = true
		prefix := ""
		if field.Optional {
			prefix = "*"
		}
		if field.Type == "string" {
			g.P(field.Name, " ", prefix, "string")
		} else {
			if !token.IsIdentifier(field.Type) {
				return fmt.Errorf("invalid state type %q", field.Type)
			}
			g.P(field.Name, " ", prefix, protogen.GoIdent{GoName: field.Type, GoImportPath: sandboxPath})
		}
	}
	g.P("}")
	if runtime.Constructor.Function != "" {
		if !token.IsIdentifier(runtime.Constructor.Function) {
			return fmt.Errorf("invalid SDK constructor %q", runtime.Constructor.Function)
		}
		g.P("func newBackend(config *", protogen.GoIdent{GoName: "Config", GoImportPath: sandboxPath}, ")(", protogen.GoIdent{GoName: "Backend", GoImportPath: sandboxPath}, ",error){")
		g.P("if config==nil {config=&sandbox.Config{}}")
		g.P("params,err:=mapClientConfig(config);if err!=nil{return nil,err}")
		g.P("native,err:=", protogen.GoIdent{GoName: runtime.Constructor.Function, GoImportPath: client.GoImportPath}, "(&params);if err!=nil{return nil,err}")
		g.P("result:=&", name, "{client:native}")
		g.P("captureBackendState(result,config);return result,nil}")
		g.P("func captureBackendState(result *", name, ",config *", protogen.GoIdent{GoName: "Config", GoImportPath: sandboxPath}, "){")
		g.P("if config==nil{return}")
		for _, field := range runtime.State {
			if field.Capture != "" {
				if err := capture(g, plugin, field.Capture, field.Type, field.Optional, "result."+field.Name); err != nil {
					return err
				}
			}
		}
		g.P("}")
	}
	g.P("func(*", name, ")Name()string{return ", strconv.Quote(spec.GetProviderName()), "}")
	g.P("func(a *", name, ")Create(ctx ", protogen.GoIdent{GoName: "Context", GoImportPath: "context"}, ",request *", request, ")(*", response, ",error){return a.create(ctx,request)}")
	if !token.IsIdentifier(runtime.Cleanup.Method) {
		return fmt.Errorf("%s: SDK cleanup binding is required", file.Desc.Path())
	}
	g.P("func(a *", name, ")Close(ctx context.Context)error{")
	args := ""
	if runtime.Cleanup.AcceptsContext {
		args = "ctx"
	}
	if runtime.Cleanup.ReturnsError {
		g.P("return a.client.", runtime.Cleanup.Method, "(", args, ")")
	} else {
		g.P("a.client.", runtime.Cleanup.Method, "(", args, ");return nil")
	}
	g.P("}")
	g.P("var _ ", protogen.GoIdent{GoName: "Provider", GoImportPath: sandboxPath}, "=(*Provider)(nil)")
	g.P("var _ ", protogen.GoIdent{GoName: "Backend", GoImportPath: sandboxPath}, "=(*", name, ")(nil)")
	return nil
}
