package declarationgen

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// Banner explains a generated file and shows one calling example.
func Banner(g *protogen.GeneratedFile, headline, summary, example string) {
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	if headline != "" {
		for _, line := range wrapComment(headline) {
			g.P("// ", line)
		}
	}
	for _, line := range strings.Split(summary, "\n") {
		for _, wrapped := range wrapComment(line) {
			g.P("// ", wrapped)
		}
	}
	if example == "" {
		return
	}
	g.P("//")
	g.P("// Example:")
	g.P("//")
	for _, line := range strings.Split(strings.Trim(example, "\n"), "\n") {
		if strings.TrimSpace(line) == "" {
			g.P("//")
			continue
		}
		g.P("//\t", line)
	}
}
