// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/adapters/modal/v1/adapter.proto

package modal

import (
	errors "errors"
	core "github.com/sandbox-kit/kit/sdks/go/core"
)

// Adapter borrows an opaque SDK client without importing that SDK.
// Construct it with New; its zero value is not ready for use.
type Adapter[C any] struct{ client *C }

// New preserves the supplied client's authentication and configuration.
// It makes no network calls and does not take ownership of the client's lifetime.
func New[C any](client *C) (*Adapter[C], error) {
	if client == nil {
		return nil, errors.New("sandbox-kit modal: SDK client is required")
	}
	return &Adapter[C]{client: client}, nil
}

// ProviderName identifies the adapter without contacting the provider.
func (*Adapter[C]) ProviderName() string { return "modal" }

var _ core.Provider = (*Adapter[struct{}])(nil)
