package adaptergen

import (
	"fmt"
	"go/token"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	codegenv1 "github.com/sandbox-kit/kit/tooling/internal/gen/codegen/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

// Generate emits an SDK-independent adapter. Typed bridges belong to the app.
func Generate(plugin *protogen.Plugin, file *protogen.File) error {
	options := file.Desc.Options()
	if !proto.HasExtension(options, codegenv1.E_Adapter) {
		return nil
	}
	if proto.HasExtension(options, codegenv1.E_Client) {
		return fmt.Errorf("%s: declare client and adapter in separate files", file.Desc.Path())
	}
	spec := proto.GetExtension(options, codegenv1.E_Adapter).(*codegenv1.AdapterDeclaration)
	name := spec.GetName()
	const constructor = "New" // Idiomatic Go naming stays in this emitter.
	for _, ident := range []string{name, constructor} {
		first, _ := utf8.DecodeRuneInString(ident)
		if !token.IsIdentifier(ident) || !unicode.IsUpper(first) {
			return fmt.Errorf("%s: adapter names must be exported Go identifiers: %q", file.Desc.Path(), ident)
		}
	}
	if name == constructor || name == "C" {
		return fmt.Errorf("%s: adapter declarations collide", file.Desc.Path())
	}
	if strings.TrimSpace(spec.GetProviderName()) == "" {
		return fmt.Errorf("%s: provider name is required", file.Desc.Path())
	}
	coreProvider := protogen.GoIdent{GoName: "Provider", GoImportPath: "github.com/sandbox-kit/kit/sdks/go/core"}
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".kit.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("// ", name, " borrows an opaque SDK client without importing that SDK.")
	g.P("// Construct it with ", constructor, "; its zero value is not ready for use.")
	g.P("type ", name, "[C any] struct { client *C }")
	g.P()
	g.P("// ", constructor, " preserves the supplied client's authentication and configuration.")
	g.P("// It makes no network calls and does not take ownership of the client's lifetime.")
	g.P("func ", constructor, "[C any](client *C) (*", name, "[C], error) {")
	g.P("if client == nil { return nil, ", protogen.GoIdent{GoName: "New", GoImportPath: "errors"}, "(", strconv.Quote("sandbox-kit "+spec.GetProviderName()+": SDK client is required"), ") }")
	g.P("return &", name, "[C]{client: client}, nil")
	g.P("}")
	g.P()
	g.P("// ProviderName identifies the adapter without contacting the provider.")
	g.P("func (*", name, "[C]) ProviderName() string { return ", strconv.Quote(spec.GetProviderName()), " }")
	g.P()
	g.P("var _ ", coreProvider, " = (*", name, "[struct{}])(nil)")
	return nil
}
