// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/providers/modal/v1/provider.proto
package modal

import (
	context "context"
	_go "github.com/modal-labs/modal-client/go"
	sandbox "github.com/sandbox-kit/kit/sdks/go/sandbox"
)

// Provider initializes the provider SDK from sandbox.Config.
type Provider struct{}

// New selects this provider; SDK initialization happens in sandbox.NewClient.
func New() *Provider           { return &Provider{} }
func (*Provider) Name() string { return "modal" }
func (*Provider) NewClient(config *sandbox.Config) (sandbox.Backend, error) {
	return newBackend(config)
}

// backend owns its initialized SDK; it is returned by the factory.
type backend struct {
	client *_go.Client
	scope  *sandbox.Scope
	region string
}

func (*backend) Name() string { return "modal" }
func (a *backend) Create(ctx context.Context, request *sandbox.CreateOptions) (*sandbox.CreateResult, error) {
	return a.create(ctx, request)
}
func (a *backend) Close(ctx context.Context) error {
	a.client.Close()
	return nil
}

var _ sandbox.Provider = (*Provider)(nil)
var _ sandbox.Backend = (*backend)(nil)
