// Code generated by protoc-gen-kit-go. DO NOT EDIT.
package modal

import (
	fmt "fmt"
	_go "github.com/modal-labs/modal-client/go"
	sandbox "github.com/sandbox-kit/kit/sdks/go/sandbox"
)

func mapClientConfig(config *sandbox.Config) (_go.ClientParams, error) {
	var params _go.ClientParams
	if config == nil {
		config = &sandbox.Config{}
	}
	if err := sandbox.ValidateConfig(config); err != nil {
		return params, err
	}
	if config.Endpoint != nil {
		return params, fmt.Errorf("sandbox-kit modal: Endpoint cannot be configured through this SDK's public client constructor")
	}
	remaining := *config
	remaining.Provider = nil
	remaining.Timeout = nil
	remaining.Region = nil
	remaining.Auth = nil
	remaining.Scope = nil
	remaining.Endpoint = nil
	if config.Scope != nil {
		mapped, rest, err := mapClientScope(config.Scope)
		if err != nil {
			return params, err
		}
		rest.AppName = nil
		if err := sandbox.RejectUnmapped("modal client scope", &rest); err != nil {
			return params, err
		}
		params.Environment = mapped.Environment
	}
	if auth := config.GetAuth(); auth != nil {
		switch {
		case auth.TokenPair != nil:
			mapped, rest, err := mapTokenPairCredentials(auth.TokenPair)
			if err != nil {
				return params, err
			}
			if err := sandbox.RejectUnmapped("modal client token_pair", &rest); err != nil {
				return params, err
			}
			params.TokenID = mapped.TokenID
			params.TokenSecret = mapped.TokenSecret
		case auth.OAuthRefresh != nil:
			mapped, rest, err := mapOAuthAuth(auth.OAuthRefresh)
			if err != nil {
				return params, err
			}
			if err := sandbox.RejectUnmapped("modal client oauth_refresh", &rest); err != nil {
				return params, err
			}
			params.OAuthCredentials = &mapped
		default:
			return params, fmt.Errorf("sandbox-kit modal: unsupported authentication mode")
		}
	}
	if err := sandbox.RejectUnmapped("modal client", &remaining); err != nil {
		return params, err
	}
	return params, nil
}
