package typesgen

import (
	"fmt"
	"strings"

	codegen "github.com/sandbox-kit/kit/tooling/internal/gen/codegen/v1"
	"github.com/sandbox-kit/kit/tooling/internal/go/naming"
	validationgen "github.com/sandbox-kit/kit/tooling/internal/go/validation_gen"
	"github.com/sandbox-kit/kit/tooling/internal/spec"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Generate emits native Go data types. Protobuf is only a build-time input.
func Generate(plugin *protogen.Plugin, file *protogen.File, rules spec.Validation, client spec.Client) error {
	if !proto.HasExtension(file.Desc.Options(), codegen.E_NativeTypes) || !proto.GetExtension(file.Desc.Options(), codegen.E_NativeTypes).(bool) {
		return nil
	}
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".types.gen.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("package ", file.GoPackageName)
	for _, enum := range file.Enums {
		name := enum.GoIdent.GoName
		g.P("type ", name, " int32")
		g.P("const (")
		for _, value := range enum.Values {
			g.P(naming.EnumValueName(value), " ", name, " = ", int32(value.Desc.Number()))
		}
		g.P(")")
		g.P("// Valid reports whether the value is declared in the shared schema.")
		g.P("func(x ", name, ")Valid()bool{switch x{")
		seen := map[int32]bool{}
		for _, value := range enum.Values {
			n := int32(value.Desc.Number())
			if !seen[n] {
				g.P("case ", n, ":return true")
				seen[n] = true
			}
		}
		g.P("default:return false}}")
		g.P("// String returns the stable schema identifier for diagnostics.")
		g.P("func(x ", name, ")String()string{switch x{")
		seen = map[int32]bool{}
		for _, value := range enum.Values {
			n := int32(value.Desc.Number())
			if !seen[n] {
				g.P("case ", n, ":return ", fmt.Sprintf("%q", string(value.Desc.Name())))
				seen[n] = true
			}
		}
		g.P("default:return \"UNKNOWN\"}}")
	}
	for _, message := range file.Messages {
		if message.Desc.IsMapEntry() {
			continue
		}
		name := message.GoIdent.GoName
		g.P("type ", name, " struct {")
		if name == client.ConfigMessage {
			g.P("// Provider constructs an SDK from this configuration; it is never serialized.")
			g.P("Provider ", client.ProviderContract, " `json:\"-\" validate:\"-\"`")
		}
		for _, field := range message.Fields {
			kind, err := fieldType(g, field)
			if err != nil {
				return err
			}
			tags := validationgen.Tags(rules.Messages[name].Fields[string(field.Desc.Name())], field.Desc.HasPresence(), field.Desc.IsList() && field.Message != nil)
			jsonName := string(field.Desc.Name())
			if explicit := field.Desc.JSONName(); explicit != defaultJSONName(jsonName) {
				jsonName = explicit
			}
			// Empty collections are explicit configuration; nil is unspecified.
			// Omitting both loses that distinction when copying declarative data.
			if !field.Desc.IsList() && !field.Desc.IsMap() {
				jsonName += ",omitempty"
			}
			if rules.Messages[name].Fields[string(field.Desc.Name())].Sensitive {
				jsonName = "-"
			}
			g.P(naming.FieldName(field), " ", kind, " `json:\"", jsonName, "\" validate:\"", tags, "\"`")
		}
		g.P("}")
		for _, field := range message.Fields {
			kind, err := fieldType(g, field)
			if err != nil {
				return err
			}
			optional := scalarPointer(field)
			resultKind := kind
			if optional {
				resultKind = strings.TrimPrefix(kind, "*")
			}
			g.P("func (x *", name, ") Get", naming.FieldName(field), "() ", resultKind, " {")
			if optional {
				g.P("if x != nil && x.", naming.FieldName(field), " != nil { return *x.", naming.FieldName(field), " }")
			} else {
				g.P("if x != nil { return x.", naming.FieldName(field), " }")
			}
			g.P("var zero ", resultKind, "; return zero }")
		}
	}
	for _, message := range file.Messages {
		if message.GoIdent.GoName == "CreateOptions" {
			g.P("// Value marks an optional scalar as explicitly supplied, including zero/false.")
			g.P("func Value[T any](value T) *T { return &value }")
		}
	}
	return nil
}

// GenerateCopies emits owned copies of native shared messages from descriptors.
func GenerateCopies(plugin *protogen.Plugin, file *protogen.File, maxDepth int) error {
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".copy.gen.go", file.GoImportPath)
	g.P("// Code generated from shared schema. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	for _, m := range file.Messages {
		if m.Desc.IsMapEntry() {
			continue
		}
		g.P("// Clone returns an owned copy, preserving field presence and numeric types.")
		g.P("// It rejects unsupported metadata and excessive depth or cycles.")
		g.P("func(x *", m.GoIdent.GoName, ")Clone()(*", m.GoIdent.GoName, ",error){return x.clone(0)}")
		g.P("func(x *", m.GoIdent.GoName, ")clone(depth int)(*", m.GoIdent.GoName, ",error){if x==nil{return nil,nil};if depth>", maxDepth, "{return nil,", protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}, "(\"sandbox-kit: data exceeds maximum copy depth or contains a cycle\")};out:=*x")
		for _, f := range m.Fields {
			name := naming.FieldName(f)
			source := "x." + name
			dest := "out." + name
			switch {
			case f.Message != nil && (f.Message.Desc.FullName() == "google.protobuf.Struct" || f.Message.Desc.FullName() == "kit.sandbox.v1.MetadataObject"):
				g.P("if ", source, "!=nil{value,err:=cloneMetadata(", source, ");if err!=nil{return nil,err};", dest, "=value}")
			case f.Desc.IsMap():
				kind, err := fieldType(g, f)
				if err != nil {
					return err
				}
				g.P("if ", source, "!=nil{", dest, "=make(", kind, ",len(", source, "));for key,value:=range ", source, "{")
				if f.Message.Fields[1].Message != nil {
					g.P("copied,err:=value.clone(depth+1);if err!=nil{return nil,err};", dest, "[key]=copied")
				} else {
					g.P(dest, "[key]=value")
				}
				g.P("}}")
			case f.Desc.Kind() == protoreflect.BytesKind:
				if scalarPointer(f) {
					g.P("if ", source, "!=nil{var value []byte;if *", source, "!=nil{value=append([]byte{},(*", source, ")...)};", dest, "=&value}")
				} else {
					g.P("if ", source, "!=nil{", dest, "=append([]byte{},", source, "...)}")
				}
			case f.Desc.IsList():
				kind, err := fieldType(g, f)
				if err != nil {
					return err
				}
				g.P("if ", source, "!=nil{", dest, "=make(", kind, ",len(", source, "));for i,value:=range ", source, "{")
				if f.Message != nil {
					g.P("copied,err:=value.clone(depth+1);if err!=nil{return nil,err};", dest, "[i]=copied")
				} else {
					g.P(dest, "[i]=value")
				}
				g.P("}}")
			case f.Message != nil && (f.Message.Desc.FullName() == "google.protobuf.Duration" || f.Message.Desc.FullName() == "google.protobuf.Timestamp"):
				g.P("if ", source, "!=nil{value:=*", source, ";", dest, "=&value}")
			case f.Message != nil:
				g.P("{value,err:=", source, ".clone(depth+1);if err!=nil{return nil,err};", dest, "=value}")
			case scalarPointer(f):
				g.P("if ", source, "!=nil{value:=*", source, ";", dest, "=&value}")
			}
		}
		g.P("return &out,nil}")
	}
	return nil
}

func scalarPointer(field *protogen.Field) bool {
	return field.Desc.HasPresence() && field.Desc.Kind() != protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap()
}
func fieldType(g *protogen.GeneratedFile, field *protogen.Field) (string, error) {
	if field.Desc.IsMap() {
		key, err := fieldType(g, field.Message.Fields[0])
		if err != nil {
			return "", err
		}
		value, err := fieldType(g, field.Message.Fields[1])
		return "map[" + key + "]" + value, err
	}
	var kind string
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		kind = "string"
	case protoreflect.BoolKind:
		kind = "bool"
	case protoreflect.DoubleKind:
		kind = "float64"
	case protoreflect.Uint32Kind:
		kind = "uint32"
	case protoreflect.Uint64Kind:
		kind = "uint64"
	case protoreflect.Int64Kind:
		kind = "int64"
	case protoreflect.BytesKind:
		kind = "[]byte"
	case protoreflect.EnumKind:
		kind = g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.MessageKind:
		switch string(field.Message.Desc.FullName()) {
		case "google.protobuf.Duration":
			kind = "*" + g.QualifiedGoIdent(protogen.GoIdent{GoName: "Duration", GoImportPath: "time"})
		case "google.protobuf.Timestamp":
			kind = "*" + g.QualifiedGoIdent(protogen.GoIdent{GoName: "Time", GoImportPath: "time"})
		case "google.protobuf.Struct":
			kind = "map[string]any"
		case "kit.sandbox.v1.MetadataObject":
			kind = "map[string]any"
		default:
			kind = "*" + g.QualifiedGoIdent(field.Message.GoIdent)
		}
	default:
		return "", fmt.Errorf("native Go generation does not support field %s", field.Desc.FullName())
	}
	if field.Desc.IsList() {
		return "[]" + kind, nil
	}
	if scalarPointer(field) {
		return "*" + kind, nil
	}
	return kind, nil
}

// Protoc populates JSONName even when the schema did not explicitly set it.
// Keep historical snake_case keys unless JSONName overrides protobuf's default.
func defaultJSONName(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
