package typesgen

import (
	"fmt"
	"strings"

	codegen "github.com/sandbox-kit/kit/tooling/internal/gen/codegen/v1"
	declarationgen "github.com/sandbox-kit/kit/tooling/internal/go/declaration_gen"
	"github.com/sandbox-kit/kit/tooling/internal/go/naming"
	validationgen "github.com/sandbox-kit/kit/tooling/internal/go/validation_gen"
	"github.com/sandbox-kit/kit/tooling/internal/model"
	"github.com/sandbox-kit/kit/tooling/internal/spec"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Generate emits native Go data types. Protobuf is only a build-time input.
func Generate(plugin *protogen.Plugin, file *protogen.File, rules spec.Validation, surface model.APIModule, helpers model.APIModule, profile spec.LanguageProfile, templates model.Templates) error {
	if !proto.HasExtension(file.Desc.Options(), codegen.E_NativeTypes) || !proto.GetExtension(file.Desc.Options(), codegen.E_NativeTypes).(bool) {
		return nil
	}
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".types.gen.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-kit-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("package ", file.GoPackageName)
	for _, enum := range file.Enums {
		name := enum.GoIdent.GoName
		g.P("type ", name, " int32")
		g.P("const (")
		for _, value := range enum.Values {
			g.P(naming.EnumValueName(value), " ", name, " = ", int32(value.Desc.Number()))
		}
		g.P(")")
		g.P("// Valid reports whether the value is declared in the shared schema.")
		g.P("func(x ", name, ")Valid()bool{switch x{")
		seen := map[int32]bool{}
		for _, value := range enum.Values {
			n := int32(value.Desc.Number())
			if !seen[n] {
				g.P("case ", n, ":return true")
				seen[n] = true
			}
		}
		g.P("default:return false}}")
		g.P("// String returns the stable schema identifier for diagnostics.")
		g.P("func(x ", name, ")String()string{switch x{")
		seen = map[int32]bool{}
		for _, value := range enum.Values {
			n := int32(value.Desc.Number())
			if !seen[n] {
				g.P("case ", n, ":return ", fmt.Sprintf("%q", string(value.Desc.Name())))
				seen[n] = true
			}
		}
		g.P("default:return \"UNKNOWN\"}}")
	}
	for _, message := range file.Messages {
		if message.Desc.IsMapEntry() {
			continue
		}
		name := message.GoIdent.GoName
		g.P("type ", name, " struct {")
		for _, attachment := range surface.Attachments {
			if attachment.Target != "schema."+string(message.Desc.Name()) {
				continue
			}
			d, err := declarationgen.New(g, plugin, model.APIModule{TypesByID: surface.TypesByID}, profile, nil)
			if err != nil {
				return err
			}
			for _, field := range attachment.Fields {
				kind, err := d.Type(field.Type)
				if err != nil {
					return err
				}
				if message.Desc.Fields().ByName(protoreflect.Name(field.Name)) != nil {
					return fmt.Errorf("runtime attachment collides with schema field %s", field.Name)
				}
				g.P("// ", field.Name, " ", field.Doc)
				g.P(field.Name, " ", kind, " `json:\"-\" validate:\"-\"`")
			}
		}
		for _, field := range message.Fields {
			kind, err := fieldType(g, field)
			if err != nil {
				return err
			}
			tags := validationgen.Tags(rules.Messages[name].Fields[string(field.Desc.Name())], field.Desc.HasPresence(), field.Desc.IsList() && field.Message != nil)
			jsonName := string(field.Desc.Name())
			if explicit := field.Desc.JSONName(); explicit != defaultJSONName(jsonName) {
				jsonName = explicit
			}
			// Empty collections are explicit configuration; nil is unspecified.
			// Omitting both loses that distinction when copying declarative data.
			if !field.Desc.IsList() && !field.Desc.IsMap() {
				jsonName += ",omitempty"
			}
			if rules.Messages[name].Fields[string(field.Desc.Name())].Sensitive {
				jsonName = "-"
			}
			g.P(naming.FieldName(field), " ", kind, " `json:\"", jsonName, "\" validate:\"", tags, "\"`")
		}
		g.P("}")
		for _, field := range message.Fields {
			kind, err := fieldType(g, field)
			if err != nil {
				return err
			}
			optional := scalarPointer(field)
			resultKind := kind
			if optional {
				resultKind = strings.TrimPrefix(kind, "*")
			}
			projection, err := model.FieldType(field.Desc, true)
			if err != nil {
				return err
			}
			d, c, err := (declarationgen.TemplateEmitter{G: g, Plugin: plugin, Templates: templates, Profile: profile}).Begin("getter", declarationgen.TemplateBindings{Names: map[string]string{"subject": name, "field": naming.FieldName(field)}, Types: map[string]spec.TypeRef{"field_value": projection}})
			if err != nil {
				return err
			}
			if optional {
				d.Body(c, "if ", d.Receiver(c), " != nil && ", d.Receiver(c), ".", naming.FieldName(field), " != nil { return *", d.Receiver(c), ".", naming.FieldName(field), " }")
			} else {
				d.Body(c, "if ", d.Receiver(c), " != nil { return ", d.Receiver(c), ".", naming.FieldName(field), " }")
			}
			d.Body(c, "var zero ", resultKind, ";return zero")
			g.P("}")
		}
	}
	for _, message := range file.Messages {
		if message.GoIdent.GoName == "CreateOptions" {
			g.P("// Value marks an optional scalar as explicitly supplied, including zero/false.")
			d, err := declarationgen.New(g, plugin, helpers, profile, nil)
			if err != nil {
				return err
			}
			value, err := d.BeginBehavior("", "value", "value")
			if err != nil {
				return err
			}
			d.Body(value, "return &", d.Param(value, "value"))
			g.P("}")
		}
	}
	return nil
}

// GenerateCopies emits owned copies of native shared messages from descriptors.
func GenerateCopies(plugin *protogen.Plugin, file *protogen.File, maxDepth int, templates model.Templates, profile spec.LanguageProfile) error {
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".copy.gen.go", file.GoImportPath)
	g.P("// Code generated from shared schema. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	for _, m := range file.Messages {
		if m.Desc.IsMapEntry() {
			continue
		}
		g.P("// Clone returns an owned copy, preserving field presence and numeric types.")
		g.P("// It rejects unsupported metadata and excessive depth or cycles.")
		emitter := declarationgen.TemplateEmitter{G: g, Plugin: plugin, Templates: templates, Profile: profile}
		d, c, err := emitter.Begin("clone", declarationgen.TemplateBindings{Names: map[string]string{"subject": m.GoIdent.GoName}})
		if err != nil {
			return err
		}
		internal, err := templates.Instantiate("clone_internal", nil)
		if err != nil {
			return err
		}
		d.Body(c, "return ", d.Receiver(c), ".", internal.Declaration.Name, "(0)")
		g.P("}")
		d, c, err = emitter.Begin("clone_internal", declarationgen.TemplateBindings{Names: map[string]string{"subject": m.GoIdent.GoName}})
		if err != nil {
			return err
		}
		d.Body(c, "if ", d.Receiver(c), "==nil{return nil,nil};if ", d.Param(c, "depth"), ">", maxDepth, "{return nil,", protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}, "(\"sandbox-kit: data exceeds maximum copy depth or contains a cycle\")};out:=*", d.Receiver(c))
		for _, f := range m.Fields {
			name := naming.FieldName(f)
			source := d.Receiver(c) + "." + name
			dest := "out." + name
			switch {
			case f.Message != nil && (f.Message.Desc.FullName() == "google.protobuf.Struct" || f.Message.Desc.FullName() == "kit.sandbox.v1.MetadataObject"):
				d.Body(c, "if ", source, "!=nil{value,err:=cloneMetadata(", source, ");if err!=nil{return nil,err};", dest, "=value}")
			case f.Desc.IsMap():
				kind, err := fieldType(g, f)
				if err != nil {
					return err
				}
				d.Body(c, "if ", source, "!=nil{", dest, "=make(", kind, ",len(", source, "));for key,value:=range ", source, "{")
				if f.Message.Fields[1].Message != nil {
					d.Body(c, "copied,err:=value."+internal.Declaration.Name+"(depth+1);if err!=nil{return nil,err};", dest, "[key]=copied")
				} else {
					d.Body(c, dest, "[key]=value")
				}
				d.Body(c, "}}")
			case f.Desc.Kind() == protoreflect.BytesKind:
				if scalarPointer(f) {
					d.Body(c, "if ", source, "!=nil{var value []byte;if *", source, "!=nil{value=append([]byte{},(*", source, ")...)};", dest, "=&value}")
				} else {
					d.Body(c, "if ", source, "!=nil{", dest, "=append([]byte{},", source, "...)}")
				}
			case f.Desc.IsList():
				kind, err := fieldType(g, f)
				if err != nil {
					return err
				}
				d.Body(c, "if ", source, "!=nil{", dest, "=make(", kind, ",len(", source, "));for i,value:=range ", source, "{")
				if f.Message != nil {
					d.Body(c, "copied,err:=value."+internal.Declaration.Name+"(depth+1);if err!=nil{return nil,err};", dest, "[i]=copied")
				} else {
					d.Body(c, dest, "[i]=value")
				}
				d.Body(c, "}}")
			case f.Message != nil && (f.Message.Desc.FullName() == "google.protobuf.Duration" || f.Message.Desc.FullName() == "google.protobuf.Timestamp"):
				d.Body(c, "if ", source, "!=nil{value:=*", source, ";", dest, "=&value}")
			case f.Message != nil:
				d.Body(c, "{value,err:=", source, "."+internal.Declaration.Name+"(depth+1);if err!=nil{return nil,err};", dest, "=value}")
			case scalarPointer(f):
				d.Body(c, "if ", source, "!=nil{value:=*", source, ";", dest, "=&value}")
			}
		}
		d.Body(c, "return &out,nil")
		g.P("}")
	}
	return nil
}

func scalarPointer(field *protogen.Field) bool {
	return field.Desc.HasPresence() && field.Desc.Kind() != protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap()
}
func fieldType(g *protogen.GeneratedFile, field *protogen.Field) (string, error) {
	if field.Desc.IsMap() {
		key, err := fieldType(g, field.Message.Fields[0])
		if err != nil {
			return "", err
		}
		value, err := fieldType(g, field.Message.Fields[1])
		return "map[" + key + "]" + value, err
	}
	var kind string
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		kind = "string"
	case protoreflect.BoolKind:
		kind = "bool"
	case protoreflect.DoubleKind:
		kind = "float64"
	case protoreflect.Uint32Kind:
		kind = "uint32"
	case protoreflect.Uint64Kind:
		kind = "uint64"
	case protoreflect.Int64Kind:
		kind = "int64"
	case protoreflect.BytesKind:
		kind = "[]byte"
	case protoreflect.EnumKind:
		kind = g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.MessageKind:
		switch string(field.Message.Desc.FullName()) {
		case "google.protobuf.Duration":
			kind = "*" + g.QualifiedGoIdent(protogen.GoIdent{GoName: "Duration", GoImportPath: "time"})
		case "google.protobuf.Timestamp":
			kind = "*" + g.QualifiedGoIdent(protogen.GoIdent{GoName: "Time", GoImportPath: "time"})
		case "google.protobuf.Struct":
			kind = "map[string]any"
		case "kit.sandbox.v1.MetadataObject":
			kind = "map[string]any"
		default:
			kind = "*" + g.QualifiedGoIdent(field.Message.GoIdent)
		}
	default:
		return "", fmt.Errorf("native Go generation does not support field %s", field.Desc.FullName())
	}
	if field.Desc.IsList() {
		return "[]" + kind, nil
	}
	if scalarPointer(field) {
		return "*" + kind, nil
	}
	return kind, nil
}

// Protoc populates JSONName even when the schema did not explicitly set it.
// Keep historical snake_case keys unless JSONName overrides protobuf's default.
func defaultJSONName(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
