// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/client.proto
// Native configuration and result types. A nil pointer means the caller
// omitted the value. Use Value to supply zero or false explicitly.
//
// Example:
//
//	options := &CreateOptions{Resources: &Resources{CPUCores: Value(0.5)}}
package sandbox

import (
	time "time"
)

// Config is the shared client configuration. Provider is attached by the
// generator and is not serialized.
//
// Example:
//
//	client, err := NewClient(Config{
//	    Provider: provider,
//	    Timeout:  Value(2 * time.Minute),
//	})
type Config struct {
	// Provider constructs the SDK from this configuration. It is never serialized.
	//
	// Example:
	//
	//	client, err := NewClient(Config{Provider: provider})
	Provider Provider `json:"-" validate:"-"`
	// Auth is one credential alternative. Nil lets the native SDK resolve its own
	// environment or profile.
	Auth *AuthConfig `json:"auth,omitempty" validate:"omitnil"`
	// Endpoint is the provider API URL where the integration supports an override.
	Endpoint *string `json:"endpoint,omitempty" validate:"omitnil,nonblank,http_url"`
	// Region is a region or target preference.
	Region *string `json:"region,omitempty" validate:"omitnil,nonblank"`
	// Scope is the app, environment, organization, or project scope. JSON name is
	// "context".
	Scope *Scope `json:"context,omitempty" validate:"omitnil"`
	// Timeout is the default Kit operation deadline. An explicit creation timeout
	// overrides it.
	// Nil and explicit zero add no Kit deadline.
	Timeout *time.Duration `json:"timeout,omitempty" validate:"omitnil,gte=0"`
}

// GetAuth returns Auth when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *Config) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	var zero *AuthConfig
	return zero
}

// GetEndpoint returns Endpoint when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Config) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	var zero string
	return zero
}

// GetRegion returns Region when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Config) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	var zero string
	return zero
}

// GetScope returns Scope when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Config) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	var zero *Scope
	return zero
}

// GetTimeout returns Timeout when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Config) GetTimeout() *time.Duration {
	if x != nil {
		return x.Timeout
	}
	var zero *time.Duration
	return zero
}

// AuthConfig holds exactly one credential alternative.
type AuthConfig struct {
	APIKey       *APIKeyCredentials      `json:"api_key,omitempty" validate:"omitnil"`
	TokenPair    *TokenPairCredentials   `json:"token_pair,omitempty" validate:"omitnil"`
	BearerToken  *BearerTokenCredentials `json:"bearer_token,omitempty" validate:"omitnil"`
	OAuthRefresh *OAuthCredentials       `json:"oauth_refresh,omitempty" validate:"omitnil"`
}

// GetAPIKey returns APIKey when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *AuthConfig) GetAPIKey() *APIKeyCredentials {
	if x != nil {
		return x.APIKey
	}
	var zero *APIKeyCredentials
	return zero
}

// GetTokenPair returns TokenPair when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *AuthConfig) GetTokenPair() *TokenPairCredentials {
	if x != nil {
		return x.TokenPair
	}
	var zero *TokenPairCredentials
	return zero
}

// GetBearerToken returns BearerToken when the receiver and field are present.
// A nil receiver or omitted field returns the zero value.
func (x *AuthConfig) GetBearerToken() *BearerTokenCredentials {
	if x != nil {
		return x.BearerToken
	}
	var zero *BearerTokenCredentials
	return zero
}

// GetOAuthRefresh returns OAuthRefresh when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *AuthConfig) GetOAuthRefresh() *OAuthCredentials {
	if x != nil {
		return x.OAuthRefresh
	}
	var zero *OAuthCredentials
	return zero
}

// APIKeyCredentials is an API-key credential. Daytona uses Key.
type APIKeyCredentials struct {
	// Key is the secret API key. It is excluded from generated JSON.
	Key string `json:"-" validate:"nonblank"`
}

// GetKey returns Key when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *APIKeyCredentials) GetKey() string {
	if x != nil {
		return x.Key
	}
	var zero string
	return zero
}

// TokenPairCredentials is a token-id and token-secret pair. Modal uses both
// fields.
type TokenPairCredentials struct {
	// ID is the token identifier.
	ID string `json:"-" validate:"nonblank"`
	// Secret is the token secret. It is excluded from generated JSON.
	Secret string `json:"-" validate:"nonblank"`
}

// GetID returns ID when the receiver and field are present. A nil receiver or
// omitted field returns the zero value.
func (x *TokenPairCredentials) GetID() string {
	if x != nil {
		return x.ID
	}
	var zero string
	return zero
}

// GetSecret returns Secret when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *TokenPairCredentials) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	var zero string
	return zero
}

// BearerTokenCredentials is a bearer or JWT credential. Daytona also requires
// an organization.
type BearerTokenCredentials struct {
	// Token is the bearer token. It is excluded from generated JSON.
	Token string `json:"-" validate:"nonblank"`
}

// GetToken returns Token when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *BearerTokenCredentials) GetToken() string {
	if x != nil {
		return x.Token
	}
	var zero string
	return zero
}

// OAuthCredentials is an OAuth refresh credential. Supply ClientID and exactly
// one of ClientSecret or JWTKey.
type OAuthCredentials struct {
	// RefreshToken is the refresh token. It is excluded from generated JSON.
	RefreshToken string `json:"-" validate:"nonblank"`
	// ClientID is the OAuth client identifier.
	ClientID string `json:"client_id,omitempty" validate:"nonblank"`
	// ClientSecret is one client secret. Do not set this together with JWTKey.
	ClientSecret *string `json:"-" validate:"omitnil,nonblank"`
	// JWTKey is one JWT signing key. Do not set this together with ClientSecret.
	JWTKey *string `json:"-" validate:"omitnil,nonblank"`
}

// GetRefreshToken returns RefreshToken when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *OAuthCredentials) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	var zero string
	return zero
}

// GetClientID returns ClientID when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *OAuthCredentials) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	var zero string
	return zero
}

// GetClientSecret returns ClientSecret when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *OAuthCredentials) GetClientSecret() string {
	if x != nil && x.ClientSecret != nil {
		return *x.ClientSecret
	}
	var zero string
	return zero
}

// GetJWTKey returns JWTKey when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *OAuthCredentials) GetJWTKey() string {
	if x != nil && x.JWTKey != nil {
		return *x.JWTKey
	}
	var zero string
	return zero
}

// Scope names the provider scope. Each provider accepts a subset of these
// fields.
type Scope struct {
	// AppName is the Modal app name. The app must already exist.
	AppName *string `json:"app_name,omitempty" validate:"omitnil,nonblank"`
	// Environment is the Modal environment. The example default is "main".
	Environment *string `json:"environment,omitempty" validate:"omitnil,nonblank"`
	// OrganizationID is the Daytona organization. Bearer auth requires it when the
	// SDK cannot resolve one.
	OrganizationID *string `json:"organization_id,omitempty" validate:"omitnil,nonblank"`
	// ProjectID is reserved for providers that scope work to a project. Current
	// providers reject it when supplied.
	ProjectID *string `json:"project_id,omitempty" validate:"omitnil,nonblank"`
}

// GetAppName returns AppName when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Scope) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	var zero string
	return zero
}

// GetEnvironment returns Environment when the receiver and field are present.
// A nil receiver or omitted field returns the zero value.
func (x *Scope) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	var zero string
	return zero
}

// GetOrganizationID returns OrganizationID when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *Scope) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	var zero string
	return zero
}

// GetProjectID returns ProjectID when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *Scope) GetProjectID() string {
	if x != nil && x.ProjectID != nil {
		return *x.ProjectID
	}
	var zero string
	return zero
}
