// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/client.proto
// Client owns an initialized provider SDK. Create returns a sandbox handle.
// Close releases the SDK and leaves the cloud sandbox running.
//
// Example:
//
//	client, err := NewClient(Config{
//	    Provider: provider,
//	})
//	instance, err := client.Create(ctx, nil)
//	err = client.Close(ctx)
package sandbox

import (
	context "context"
	errors "errors"
	fmt "fmt"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Backend is the local operation and SDK cleanup contract.
type Backend interface {
	// Name returns the provider identifier, such as "daytona" or "modal".
	Name() string
	// Create creates one sandbox from request. A nil request uses provider
	// defaults.
	// The result carries shared metadata. The public client turns that into a
	// Sandbox handle.
	//
	// Example:
	//
	//	result, err := backend.Create(ctx, nil)
	Create(context.Context, *CreateOptions) (*CreateResult, error)
	// Close releases the native SDK. It does not stop or delete the cloud sandbox.
	//
	// Example:
	//
	//	err := backend.Close(ctx)
	Close(context.Context) error
}

// Provider initializes the provider SDK from shared configuration.
type Provider interface {
	// Name returns the provider identifier selected by this factory.
	Name() string
	// NewClient builds a backend from shared configuration. Call it through
	// sandbox.NewClient,
	// which validates the configuration and owns cleanup.
	//
	// Example:
	//
	//	backend, err := provider.NewClient(&config)
	NewClient(*Config) (Backend, error)
}

// Client owns its initialized provider SDK. Close it when finished.
type Client struct {
	// backend is the initialized provider SDK. Applications use Client methods
	// instead of this field.
	backend Backend
	// timeout is a copy of Config.Timeout. Nil adds no Kit deadline. An explicit
	// zero also adds none.
	timeout *time.Duration
}

// missingClientBinding reports whether a provider or backend value is missing.
// Nil interfaces, pointers, slices, and maps count as missing.
func missingClientBinding(binding any) bool {
	value := reflect.ValueOf(binding)
	if !value.IsValid() {
		return true
	}
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	}
	return false
}

// NewClient validates shared configuration and initializes the selected
// provider SDK.
// The returned client owns cleanup. Closing it does not stop the sandbox.
//
// Example:
//
//	client, err := NewClient(Config{
//	    Provider: provider,
//	    Timeout:  Value(2 * time.Minute),
//	})
func NewClient(config Config) (client *Client, result error) {
	provider := ""
	defer func() { result = WithErrorContext(result, provider, "initialize") }()
	if missingClientBinding(config.Provider) {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Operation: "initialize", Field: "provider", Message: "sandbox-kit: provider is required"}, nil)
	}
	provider = config.Provider.Name()
	if err := ValidateConfig(&config); err != nil {
		return nil, err
	}
	expected := provider
	if strings.TrimSpace(expected) == "" {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Operation: "initialize", Field: "provider", Message: "sandbox-kit: provider name is required"}, nil)
	}
	var timeout *time.Duration
	if config.Timeout != nil {
		value := *config.Timeout
		timeout = &value
	}
	backend, err := config.Provider.NewClient(&config)
	if err != nil {
		return nil, err
	}
	if missingClientBinding(backend) {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidResponse, Provider: expected, Operation: "initialize", Field: "backend", Message: "sandbox-kit: provider returned no initialized backend"}, nil)
	}
	if actual := backend.Name(); actual != expected {
		return nil, errors.Join(NewError(ErrorInfo{Kind: ErrorKindInvalidResponse, Provider: expected, Operation: "initialize", Field: "provider", Message: fmt.Sprintf("sandbox-kit: initialized backend %q differs from selected provider %q", actual, expected)}, nil), backend.Close(context.Background()))
	}
	return &Client{backend: backend, timeout: timeout}, nil
}

// ProviderName returns the selected provider identifier, such as "daytona" or
// "modal".
func (c *Client) ProviderName() string {
	return c.backend.Name()
}

// Close releases the native SDK. It does not stop or delete the cloud sandbox.
// A nil client is a no-op. A nil context returns an invalid-argument error.
//
// Example:
//
//	err := client.Close(ctx)
func (c *Client) Close(ctx context.Context) (result error) {
	provider := ""
	if c != nil && c.backend != nil {
		provider = c.backend.Name()
	}
	defer func() { result = WithErrorContext(result, provider, "close") }()
	if ctx == nil {
		return NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Provider: provider, Operation: "close", Field: "context", Message: "sandbox-kit: context is required"}, nil)
	}
	if c == nil || c.backend == nil {
		return nil
	}
	return c.backend.Close(ctx)
}

// Create creates one sandbox and returns a handle. A nil request uses provider
// defaults.
// Close the client when finished; that does not delete the sandbox.
//
// Example:
//
//	instance, err := client.Create(ctx, nil)
//	fmt.Println(instance.ID(), instance.ProviderName())
func (c *Client) Create(ctx context.Context, request *CreateOptions) (instance *Sandbox, result error) {
	provider := ""
	if c != nil && c.backend != nil {
		provider = c.backend.Name()
	}
	defer func() { result = WithErrorContext(result, provider, "create") }()
	if ctx == nil {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Provider: provider, Operation: "create", Field: "context", Message: "sandbox-kit: context is required"}, nil)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if c == nil || c.backend == nil {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Provider: provider, Operation: "create", Field: "client", Message: "sandbox-kit: client is not initialized"}, nil)
	}
	request, err := prepareCreateRequest(request)
	if err != nil {
		return nil, err
	}
	timeout := request.GetProvisioning().GetTimeout()
	if timeout == nil {
		timeout = c.timeout
	}
	if timeout != nil && *timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}
	if timeout != nil {
		if request.Provisioning == nil {
			request.Provisioning = &ProvisioningOptions{}
		}
		value := *timeout
		request.Provisioning.Timeout = &value
	}
	response, err := c.backend.Create(ctx, request)
	if err != nil {
		return nil, err
	}
	return sandboxFromResponse(c.backend, response)
}
