// Code generated from shared schema paths. DO NOT EDIT.
package sandbox

const ConfigFieldAuth = "auth"
const ConfigFieldAuthAPIKey = "auth.api_key"
const ConfigFieldAuthAPIKeyKey = "auth.api_key.key"
const ConfigFieldAuthTokenPair = "auth.token_pair"
const ConfigFieldAuthTokenPairID = "auth.token_pair.id"
const ConfigFieldAuthTokenPairSecret = "auth.token_pair.secret"
const ConfigFieldAuthBearerToken = "auth.bearer_token"
const ConfigFieldAuthBearerTokenToken = "auth.bearer_token.token"
const ConfigFieldAuthOAuthRefresh = "auth.oauth_refresh"
const ConfigFieldAuthOAuthRefreshRefreshToken = "auth.oauth_refresh.refresh_token"
const ConfigFieldAuthOAuthRefreshClientID = "auth.oauth_refresh.client_id"
const ConfigFieldAuthOAuthRefreshClientSecret = "auth.oauth_refresh.client_secret"
const ConfigFieldAuthOAuthRefreshJWTKey = "auth.oauth_refresh.jwt_key"
const ConfigFieldEndpoint = "endpoint"
const ConfigFieldRegion = "region"
const ConfigFieldScope = "scope"
const ConfigFieldScopeAppName = "scope.app_name"
const ConfigFieldScopeEnvironment = "scope.environment"
const ConfigFieldScopeOrganizationID = "scope.organization_id"
const ConfigFieldScopeProjectID = "scope.project_id"
const ConfigFieldTimeout = "timeout"
const ConfigFieldProvider = "provider"
