// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/client.proto
package sandbox

import (
	time "time"
)

type Config struct {
	// Provider constructs an SDK from this configuration; it is never serialized.
	Provider Provider       `json:"-" validate:"-"`
	Auth     *AuthConfig    `json:"auth,omitempty" validate:"omitnil"`
	Endpoint *string        `json:"endpoint,omitempty" validate:"omitnil,nonblank,http_url"`
	Region   *string        `json:"region,omitempty" validate:"omitnil,nonblank"`
	Scope    *Scope         `json:"context,omitempty" validate:"omitnil"`
	Timeout  *time.Duration `json:"timeout,omitempty" validate:"omitnil,gte=0"`
}

func (x *Config) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	var zero *AuthConfig
	return zero
}
func (x *Config) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	var zero string
	return zero
}
func (x *Config) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	var zero string
	return zero
}
func (x *Config) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	var zero *Scope
	return zero
}
func (x *Config) GetTimeout() *time.Duration {
	if x != nil {
		return x.Timeout
	}
	var zero *time.Duration
	return zero
}

type AuthConfig struct {
	APIKey       *APIKeyCredentials      `json:"api_key,omitempty" validate:"omitnil"`
	TokenPair    *TokenPairCredentials   `json:"token_pair,omitempty" validate:"omitnil"`
	BearerToken  *BearerTokenCredentials `json:"bearer_token,omitempty" validate:"omitnil"`
	OAuthRefresh *OAuthCredentials       `json:"oauth_refresh,omitempty" validate:"omitnil"`
}

func (x *AuthConfig) GetAPIKey() *APIKeyCredentials {
	if x != nil {
		return x.APIKey
	}
	var zero *APIKeyCredentials
	return zero
}
func (x *AuthConfig) GetTokenPair() *TokenPairCredentials {
	if x != nil {
		return x.TokenPair
	}
	var zero *TokenPairCredentials
	return zero
}
func (x *AuthConfig) GetBearerToken() *BearerTokenCredentials {
	if x != nil {
		return x.BearerToken
	}
	var zero *BearerTokenCredentials
	return zero
}
func (x *AuthConfig) GetOAuthRefresh() *OAuthCredentials {
	if x != nil {
		return x.OAuthRefresh
	}
	var zero *OAuthCredentials
	return zero
}

type APIKeyCredentials struct {
	Key string `json:"-" validate:"nonblank"`
}

func (x *APIKeyCredentials) GetKey() string {
	if x != nil {
		return x.Key
	}
	var zero string
	return zero
}

type TokenPairCredentials struct {
	ID     string `json:"-" validate:"nonblank"`
	Secret string `json:"-" validate:"nonblank"`
}

func (x *TokenPairCredentials) GetID() string {
	if x != nil {
		return x.ID
	}
	var zero string
	return zero
}
func (x *TokenPairCredentials) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	var zero string
	return zero
}

type BearerTokenCredentials struct {
	Token string `json:"-" validate:"nonblank"`
}

func (x *BearerTokenCredentials) GetToken() string {
	if x != nil {
		return x.Token
	}
	var zero string
	return zero
}

type OAuthCredentials struct {
	RefreshToken string  `json:"-" validate:"nonblank"`
	ClientID     string  `json:"client_id,omitempty" validate:"nonblank"`
	ClientSecret *string `json:"-" validate:"omitnil,nonblank"`
	JWTKey       *string `json:"-" validate:"omitnil,nonblank"`
}

func (x *OAuthCredentials) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	var zero string
	return zero
}
func (x *OAuthCredentials) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	var zero string
	return zero
}
func (x *OAuthCredentials) GetClientSecret() string {
	if x != nil && x.ClientSecret != nil {
		return *x.ClientSecret
	}
	var zero string
	return zero
}
func (x *OAuthCredentials) GetJWTKey() string {
	if x != nil && x.JWTKey != nil {
		return *x.JWTKey
	}
	var zero string
	return zero
}

type Scope struct {
	AppName        *string `json:"app_name,omitempty" validate:"omitnil,nonblank"`
	Environment    *string `json:"environment,omitempty" validate:"omitnil,nonblank"`
	OrganizationID *string `json:"organization_id,omitempty" validate:"omitnil,nonblank"`
	ProjectID      *string `json:"project_id,omitempty" validate:"omitnil,nonblank"`
}

func (x *Scope) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	var zero string
	return zero
}
func (x *Scope) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	var zero string
	return zero
}
func (x *Scope) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	var zero string
	return zero
}
func (x *Scope) GetProjectID() string {
	if x != nil && x.ProjectID != nil {
		return *x.ProjectID
	}
	var zero string
	return zero
}
