// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// Field-path constants identify settings in errors. Their values are canonical
// protobuf paths.
//
// Example:
//
//	fmt.Println(CreateFieldResourcesCPUCores) // resources.cpu_cores
package sandbox

// ConfigFieldAuth is the canonical path "auth".
const ConfigFieldAuth = "auth"

// ConfigFieldAuthAPIKey is the canonical path "auth.api_key".
const ConfigFieldAuthAPIKey = "auth.api_key"

// ConfigFieldAuthAPIKeyKey is the canonical path "auth.api_key.key".
const ConfigFieldAuthAPIKeyKey = "auth.api_key.key"

// ConfigFieldAuthTokenPair is the canonical path "auth.token_pair".
const ConfigFieldAuthTokenPair = "auth.token_pair"

// ConfigFieldAuthTokenPairID is the canonical path "auth.token_pair.id".
const ConfigFieldAuthTokenPairID = "auth.token_pair.id"

// ConfigFieldAuthTokenPairSecret is the canonical path
// "auth.token_pair.secret".
const ConfigFieldAuthTokenPairSecret = "auth.token_pair.secret"

// ConfigFieldAuthBearerToken is the canonical path "auth.bearer_token".
const ConfigFieldAuthBearerToken = "auth.bearer_token"

// ConfigFieldAuthBearerTokenToken is the canonical path
// "auth.bearer_token.token".
const ConfigFieldAuthBearerTokenToken = "auth.bearer_token.token"

// ConfigFieldAuthOAuthRefresh is the canonical path "auth.oauth_refresh".
const ConfigFieldAuthOAuthRefresh = "auth.oauth_refresh"

// ConfigFieldAuthOAuthRefreshRefreshToken is the canonical path
// "auth.oauth_refresh.refresh_token".
const ConfigFieldAuthOAuthRefreshRefreshToken = "auth.oauth_refresh.refresh_token"

// ConfigFieldAuthOAuthRefreshClientID is the canonical path
// "auth.oauth_refresh.client_id".
const ConfigFieldAuthOAuthRefreshClientID = "auth.oauth_refresh.client_id"

// ConfigFieldAuthOAuthRefreshClientSecret is the canonical path
// "auth.oauth_refresh.client_secret".
const ConfigFieldAuthOAuthRefreshClientSecret = "auth.oauth_refresh.client_secret"

// ConfigFieldAuthOAuthRefreshJWTKey is the canonical path
// "auth.oauth_refresh.jwt_key".
const ConfigFieldAuthOAuthRefreshJWTKey = "auth.oauth_refresh.jwt_key"

// ConfigFieldEndpoint is the canonical path "endpoint".
const ConfigFieldEndpoint = "endpoint"

// ConfigFieldRegion is the canonical path "region".
const ConfigFieldRegion = "region"

// ConfigFieldScope is the canonical path "scope".
const ConfigFieldScope = "scope"

// ConfigFieldScopeAppName is the canonical path "scope.app_name".
const ConfigFieldScopeAppName = "scope.app_name"

// ConfigFieldScopeEnvironment is the canonical path "scope.environment".
const ConfigFieldScopeEnvironment = "scope.environment"

// ConfigFieldScopeOrganizationID is the canonical path
// "scope.organization_id".
const ConfigFieldScopeOrganizationID = "scope.organization_id"

// ConfigFieldScopeProjectID is the canonical path "scope.project_id".
const ConfigFieldScopeProjectID = "scope.project_id"

// ConfigFieldTimeout is the canonical path "timeout".
const ConfigFieldTimeout = "timeout"

// ConfigFieldProvider is the canonical path "provider".
const ConfigFieldProvider = "provider"
