// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/client.proto
package sandbox

import (
	context "context"
	errors "errors"
	fmt "fmt"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Backend is the full local operation and resource-ownership contract.
type Backend interface {
	Name() string
	Create(context.Context, *CreateOptions) (*CreateResult, error)
	Close(context.Context) error
}

// Provider initializes an SDK from the shared client configuration.
type Provider interface {
	Name() string
	NewClient(*Config) (Backend, error)
}

// Client owns its initialized provider SDK. Close it when finished.
type Client struct {
	backend Backend
	timeout *time.Duration
}

func missingClientBinding(binding any) bool {
	value := reflect.ValueOf(binding)
	if !value.IsValid() {
		return true
	}
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	}
	return false
}

// NewClient validates common configuration before initializing the selected SDK.
func NewClient(config Config) (client *Client, result error) {
	provider := ""
	defer func() { result = WithErrorContext(result, provider, "initialize") }()
	if missingClientBinding(config.Provider) {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Operation: "initialize", Field: "provider", Message: "sandbox-kit: provider is required"}, nil)
	}
	provider = config.Provider.Name()
	if err := ValidateConfig(&config); err != nil {
		return nil, err
	}
	expected := provider
	if strings.TrimSpace(expected) == "" {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Operation: "initialize", Field: "provider", Message: "sandbox-kit: provider name is required"}, nil)
	}
	var timeout *time.Duration
	if config.Timeout != nil {
		value := *config.Timeout
		timeout = &value
	}
	backend, err := config.Provider.NewClient(&config)
	if err != nil {
		return nil, err
	}
	if missingClientBinding(backend) {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidResponse, Provider: expected, Operation: "initialize", Field: "backend", Message: "sandbox-kit: provider returned no initialized backend"}, nil)
	}
	if actual := backend.Name(); actual != expected {
		return nil, errors.Join(NewError(ErrorInfo{Kind: ErrorKindInvalidResponse, Provider: expected, Operation: "initialize", Field: "provider", Message: fmt.Sprintf("sandbox-kit: initialized backend %q differs from selected provider %q", actual, expected)}, nil), backend.Close(context.Background()))
	}
	return &Client{backend: backend, timeout: timeout}, nil
}
func (c *Client) ProviderName() string { return c.backend.Name() }

// Close releases resources owned by the provider SDK; it does not delete sandboxes.
func (c *Client) Close(ctx context.Context) (result error) {
	provider := ""
	if c != nil && c.backend != nil {
		provider = c.backend.Name()
	}
	defer func() { result = WithErrorContext(result, provider, "close") }()
	if ctx == nil {
		return NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Provider: provider, Operation: "close", Field: "context", Message: "sandbox-kit: context is required"}, nil)
	}
	if c == nil || c.backend == nil {
		return nil
	}
	return c.backend.Close(ctx)
}
func (c *Client) Create(ctx context.Context, request *CreateOptions) (instance *Sandbox, result error) {
	provider := ""
	if c != nil && c.backend != nil {
		provider = c.backend.Name()
	}
	defer func() { result = WithErrorContext(result, provider, "create") }()
	if ctx == nil {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Provider: provider, Operation: "create", Field: "context", Message: "sandbox-kit: context is required"}, nil)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if c == nil || c.backend == nil {
		return nil, NewError(ErrorInfo{Kind: ErrorKindInvalidArgument, Provider: provider, Operation: "create", Field: "client", Message: "sandbox-kit: client is not initialized"}, nil)
	}
	request, err := prepareCreateRequest(request)
	if err != nil {
		return nil, err
	}
	timeout := request.GetProvisioning().GetTimeout()
	if timeout == nil {
		timeout = c.timeout
	}
	if timeout != nil && *timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}
	if timeout != nil {
		if request.Provisioning == nil {
			request.Provisioning = &ProvisioningOptions{}
		}
		value := *timeout
		request.Provisioning.Timeout = &value
	}
	response, err := c.backend.Create(ctx, request)
	if err != nil {
		return nil, err
	}
	return sandboxFromResponse(c.backend, response)
}
