// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/sandbox.proto
// Validators reject values the shared contract cannot represent. They run
// before a provider call.
//
// Example:
//
//	if err := ValidateCreateOptions(value); err != nil { return err }
package sandbox

import (
	v10 "github.com/go-playground/validator/v10"
	math "math"
	strings "strings"
)

// newCreateOptionsValidator builds the validator used by
// ValidateCreateOptions.
func newCreateOptionsValidator() *v10.Validate {
	v := v10.New(v10.WithRequiredStructEnabled())
	_ = v.RegisterValidation("finite", func(fl v10.FieldLevel) bool {
		value := fl.Field().Float()
		return !math.IsNaN(value) && !math.IsInf(value, 0)
	})
	_ = v.RegisterValidation("nonblank", func(fl v10.FieldLevel) bool { return strings.TrimSpace(fl.Field().String()) != "" })
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(AutomaticAction)
		_ = x
		switch x.GetMode() {
		case 0, 1, 2:
		default:
			sl.ReportError(x, "Mode", "Mode", "known_enum", "")
		}
		count0 := 0
		if x.After != nil {
			count0++
		}
		if (x.GetMode() == 2) && (count0 == 0) {
			sl.ReportError(x, "after", "after", "requires_any", "")
		}
		count1 := 0
		if x.After != nil {
			count1++
		}
		if (x.GetMode() != 2) && (count1 > 0) {
			sl.ReportError(x, "after", "after", "forbids", "")
		}
	}, AutomaticAction{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(ErrorInfo)
		_ = x
		switch x.GetKind() {
		case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15:
		default:
			sl.ReportError(x, "Kind", "Kind", "known_enum", "")
		}
	}, ErrorInfo{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(IsolationConfig)
		_ = x
		switch x.GetKind() {
		case 0, 1, 2, 3, 4, 5:
		default:
			sl.ReportError(x, "Kind", "Kind", "known_enum", "")
		}
	}, IsolationConfig{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(NetworkConfig)
		_ = x
		switch x.GetEgress() {
		case 0, 1, 2, 3:
		default:
			sl.ReportError(x, "Egress", "Egress", "known_enum", "")
		}
		count0 := 0
		if x.OutboundCIDRs != nil {
			count0++
		}
		if x.OutboundDomains != nil {
			count0++
		}
		if (x.GetEgress() == 3) && (count0 == 0) {
			sl.ReportError(x, "outbound_cidrs,outbound_domains", "outbound_cidrs,outbound_domains", "requires_any", "")
		}
		count1 := 0
		if x.OutboundCIDRs != nil {
			count1++
		}
		if x.OutboundDomains != nil {
			count1++
		}
		if x.GetPrivateNetwork() {
			count1++
		}
		if x.LinkedSandbox != nil {
			count1++
		}
		if x.InboundCIDRs != nil {
			count1++
		}
		if len(x.Ports) > 0 {
			count1++
		}
		if (x.GetEgress() == 2) && (count1 > 0) {
			sl.ReportError(x, "outbound_cidrs,outbound_domains,private_network,linked_sandbox,inbound_cidrs,ports", "outbound_cidrs,outbound_domains,private_network,linked_sandbox,inbound_cidrs,ports", "forbids", "")
		}
		count2 := 0
		if x.OutboundCIDRs != nil {
			count2++
		}
		if x.OutboundDomains != nil {
			count2++
		}
		if (x.GetEgress() == 1) && (count2 > 0) {
			sl.ReportError(x, "outbound_cidrs,outbound_domains", "outbound_cidrs,outbound_domains", "forbids", "")
		}
	}, NetworkConfig{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(PortBinding)
		_ = x
		switch x.GetTransport() {
		case 0, 1, 2, 3:
		default:
			sl.ReportError(x, "Transport", "Transport", "known_enum", "")
		}
	}, PortBinding{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(ProvisioningOptions)
		_ = x
		switch x.GetWaitFor() {
		case 0, 1, 2, 3, 4:
		default:
			sl.ReportError(x, "WaitFor", "WaitFor", "known_enum", "")
		}
	}, ProvisioningOptions{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(ReadinessProbe)
		_ = x
		count0 := 0
		if x.TCPPort != nil {
			count0++
		}
		if x.Command != nil {
			count0++
		}
		if (true) && (count0 != 1) {
			sl.ReportError(x, "tcp_port,command", "tcp_port,command", "exactly_one", "")
		}
	}, ReadinessProbe{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(Resources)
		_ = x
		if (true) && (x.GetCPULimitCores() > 0 && x.GetCPULimitCores() < x.GetCPUCores()) {
			sl.ReportError(x, "cpu_limit_cores", "cpu_limit_cores", "limit", "")
		}
		if (true) && (x.GetMemoryLimitMiB() > 0 && x.GetMemoryLimitMiB() < x.GetMemoryMiB()) {
			sl.ReportError(x, "memory_limit_mib", "memory_limit_mib", "limit", "")
		}
		if (true) && (x.GetCPULimitCores() > 0 && x.GetCPUCores() == 0) {
			sl.ReportError(x, "cpu_limit_cores", "cpu_limit_cores", "requires_positive", "")
		}
		if (true) && (x.GetMemoryLimitMiB() > 0 && x.GetMemoryMiB() == 0) {
			sl.ReportError(x, "memory_limit_mib", "memory_limit_mib", "requires_positive", "")
		}
	}, Resources{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(SandboxSource)
		_ = x
		count0 := 0
		if x.ProviderDefault != nil {
			count0++
		}
		if x.Image != nil {
			count0++
		}
		if x.Snapshot != nil {
			count0++
		}
		if x.WarmPool != nil {
			count0++
		}
		if (true) && (count0 > 1) {
			sl.ReportError(x, "provider_default,image,snapshot,warm_pool", "provider_default,image,snapshot,warm_pool", "at_most_one", "")
		}
	}, SandboxSource{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(SecretReference)
		_ = x
		switch x.GetInjection() {
		case 0, 1, 2:
		default:
			sl.ReportError(x, "Injection", "Injection", "known_enum", "")
		}
	}, SecretReference{})
	v.RegisterStructValidation(func(sl v10.StructLevel) {
		x := sl.Current().Interface().(SnapshotSource)
		_ = x
		switch x.GetKind() {
		case 0, 1, 2, 3, 4, 5, 6:
		default:
			sl.ReportError(x, "Kind", "Kind", "known_enum", "")
		}
	}, SnapshotSource{})
	return v
}

// ValidateCreateOptions applies the generated shared rules without filling defaults.
// ValidateCreateOptions rejects CreateOptions values the shared contract
// cannot represent. A nil request is treated as omitted configuration. Account
// quotas stay with the provider.
func ValidateCreateOptions(request *CreateOptions) error {
	if request == nil {
		return nil
	}
	if err := newCreateOptionsValidator().Struct(request); err != nil {
		return validationError(err)
	}
	return nil
}
