// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/sandbox.proto
// Native configuration and result types. A nil pointer means the caller
// omitted the value. Use Value to supply zero or false explicitly.
//
// Example:
//
//	options := &CreateOptions{Resources: &Resources{CPUCores: Value(0.5)}}
package sandbox

import (
	time "time"
)

// SnapshotKind classifies a snapshot. Preserve the numeric values.
type SnapshotKind int32

const (
	SnapshotKindDefault          SnapshotKind = 0
	SnapshotKindFilesystem       SnapshotKind = 1
	SnapshotKindMemory           SnapshotKind = 2
	SnapshotKindImage            SnapshotKind = 3
	SnapshotKindMachine          SnapshotKind = 4
	SnapshotKindCheckpoint       SnapshotKind = 5
	SnapshotKindProviderSpecific SnapshotKind = 6
)

// Valid reports whether the value is declared in the shared schema.
func (x SnapshotKind) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	case 5:
		return true
	case 6:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x SnapshotKind) String() string {
	switch x {
	case 0:
		return "SNAPSHOT_KIND_DEFAULT"
	case 1:
		return "SNAPSHOT_KIND_FILESYSTEM"
	case 2:
		return "SNAPSHOT_KIND_MEMORY"
	case 3:
		return "SNAPSHOT_KIND_IMAGE"
	case 4:
		return "SNAPSHOT_KIND_MACHINE"
	case 5:
		return "SNAPSHOT_KIND_CHECKPOINT"
	case 6:
		return "SNAPSHOT_KIND_PROVIDER_SPECIFIC"
	default:
		return "UNKNOWN"
	}
}

// IsolationKind is the isolation class. Preserve the numeric values.
type IsolationKind int32

const (
	IsolationKindDefault          IsolationKind = 0
	IsolationKindContainer        IsolationKind = 1
	IsolationKindMicroVM          IsolationKind = 2
	IsolationKindLinuxVM          IsolationKind = 3
	IsolationKindWorker           IsolationKind = 4
	IsolationKindProviderSpecific IsolationKind = 5
)

// Valid reports whether the value is declared in the shared schema.
func (x IsolationKind) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	case 5:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x IsolationKind) String() string {
	switch x {
	case 0:
		return "ISOLATION_KIND_DEFAULT"
	case 1:
		return "ISOLATION_KIND_CONTAINER"
	case 2:
		return "ISOLATION_KIND_MICROVM"
	case 3:
		return "ISOLATION_KIND_LINUX_VM"
	case 4:
		return "ISOLATION_KIND_WORKER"
	case 5:
		return "ISOLATION_KIND_PROVIDER_SPECIFIC"
	default:
		return "UNKNOWN"
	}
}

// EgressMode controls outbound traffic. Default leaves the policy to the
// provider.
type EgressMode int32

const (
	EgressModeDefault  EgressMode = 0
	EgressModeAllowAll EgressMode = 1
	// EgressModeBlockAll blocks all networking, including private connections.
	EgressModeBlockAll   EgressMode = 2
	EgressModeRestricted EgressMode = 3
)

// Valid reports whether the value is declared in the shared schema.
func (x EgressMode) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x EgressMode) String() string {
	switch x {
	case 0:
		return "EGRESS_MODE_DEFAULT"
	case 1:
		return "EGRESS_MODE_ALLOW_ALL"
	case 2:
		return "EGRESS_MODE_BLOCK_ALL"
	case 3:
		return "EGRESS_MODE_RESTRICTED"
	default:
		return "UNKNOWN"
	}
}

// PortTransport is the protocol used for a published port.
type PortTransport int32

const (
	PortTransportDefault  PortTransport = 0
	PortTransportTLS      PortTransport = 1
	PortTransportHTTP2TLS PortTransport = 2
	PortTransportPlain    PortTransport = 3
)

// Valid reports whether the value is declared in the shared schema.
func (x PortTransport) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x PortTransport) String() string {
	switch x {
	case 0:
		return "PORT_TRANSPORT_DEFAULT"
	case 1:
		return "PORT_TRANSPORT_TLS"
	case 2:
		return "PORT_TRANSPORT_HTTP2_TLS"
	case 3:
		return "PORT_TRANSPORT_PLAIN"
	default:
		return "UNKNOWN"
	}
}

// SecretInjection selects how a secret is exposed to the sandbox.
type SecretInjection int32

const (
	SecretInjectionDefault           SecretInjection = 0
	SecretInjectionEnvironment       SecretInjection = 1
	SecretInjectionEgressPlaceholder SecretInjection = 2
)

// Valid reports whether the value is declared in the shared schema.
func (x SecretInjection) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x SecretInjection) String() string {
	switch x {
	case 0:
		return "SECRET_INJECTION_DEFAULT"
	case 1:
		return "SECRET_INJECTION_ENVIRONMENT"
	case 2:
		return "SECRET_INJECTION_EGRESS_PLACEHOLDER"
	default:
		return "UNKNOWN"
	}
}

// PolicyMode selects whether an automatic action is omitted, disabled, or
// delayed.
type PolicyMode int32

const (
	PolicyModeDefault  PolicyMode = 0
	PolicyModeDisabled PolicyMode = 1
	PolicyModeAfter    PolicyMode = 2
)

// Valid reports whether the value is declared in the shared schema.
func (x PolicyMode) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x PolicyMode) String() string {
	switch x {
	case 0:
		return "POLICY_MODE_DEFAULT"
	case 1:
		return "POLICY_MODE_DISABLED"
	case 2:
		return "POLICY_MODE_AFTER"
	default:
		return "UNKNOWN"
	}
}

// WaitCondition is how far creation waits before returning. Ready can require
// a probe and a positive timeout.
type WaitCondition int32

const (
	WaitConditionDefault   WaitCondition = 0
	WaitConditionSubmitted WaitCondition = 1
	WaitConditionScheduled WaitCondition = 2
	WaitConditionStarted   WaitCondition = 3
	WaitConditionReady     WaitCondition = 4
)

// Valid reports whether the value is declared in the shared schema.
func (x WaitCondition) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x WaitCondition) String() string {
	switch x {
	case 0:
		return "WAIT_CONDITION_DEFAULT"
	case 1:
		return "WAIT_CONDITION_SUBMITTED"
	case 2:
		return "WAIT_CONDITION_SCHEDULED"
	case 3:
		return "WAIT_CONDITION_STARTED"
	case 4:
		return "WAIT_CONDITION_READY"
	default:
		return "UNKNOWN"
	}
}

// ValueOrigin records whether a metadata field came from the provider or from
// the request.
type ValueOrigin int32

const (
	ValueOriginUnknown  ValueOrigin = 0
	ValueOriginProvider ValueOrigin = 1
	ValueOriginRequest  ValueOrigin = 2
)

// Valid reports whether the value is declared in the shared schema.
func (x ValueOrigin) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x ValueOrigin) String() string {
	switch x {
	case 0:
		return "VALUE_ORIGIN_UNKNOWN"
	case 1:
		return "VALUE_ORIGIN_PROVIDER"
	case 2:
		return "VALUE_ORIGIN_REQUEST"
	default:
		return "UNKNOWN"
	}
}

// ErrorKind is the shared error category. It does not imply that a retry is
// safe.
type ErrorKind int32

const (
	ErrorKindUnknown            ErrorKind = 0
	ErrorKindInvalidArgument    ErrorKind = 1
	ErrorKindUnsupported        ErrorKind = 2
	ErrorKindAuthentication     ErrorKind = 3
	ErrorKindPermissionDenied   ErrorKind = 4
	ErrorKindNotFound           ErrorKind = 5
	ErrorKindAlreadyExists      ErrorKind = 6
	ErrorKindConflict           ErrorKind = 7
	ErrorKindRateLimited        ErrorKind = 8
	ErrorKindResourceExhausted  ErrorKind = 9
	ErrorKindTimeout            ErrorKind = 10
	ErrorKindCanceled           ErrorKind = 11
	ErrorKindUnavailable        ErrorKind = 12
	ErrorKindInvalidResponse    ErrorKind = 13
	ErrorKindInternal           ErrorKind = 14
	ErrorKindFailedPrecondition ErrorKind = 15
)

// Valid reports whether the value is declared in the shared schema.
func (x ErrorKind) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	case 5:
		return true
	case 6:
		return true
	case 7:
		return true
	case 8:
		return true
	case 9:
		return true
	case 10:
		return true
	case 11:
		return true
	case 12:
		return true
	case 13:
		return true
	case 14:
		return true
	case 15:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x ErrorKind) String() string {
	switch x {
	case 0:
		return "ERROR_KIND_UNKNOWN"
	case 1:
		return "ERROR_KIND_INVALID_ARGUMENT"
	case 2:
		return "ERROR_KIND_UNSUPPORTED"
	case 3:
		return "ERROR_KIND_AUTHENTICATION"
	case 4:
		return "ERROR_KIND_PERMISSION_DENIED"
	case 5:
		return "ERROR_KIND_NOT_FOUND"
	case 6:
		return "ERROR_KIND_ALREADY_EXISTS"
	case 7:
		return "ERROR_KIND_CONFLICT"
	case 8:
		return "ERROR_KIND_RATE_LIMITED"
	case 9:
		return "ERROR_KIND_RESOURCE_EXHAUSTED"
	case 10:
		return "ERROR_KIND_TIMEOUT"
	case 11:
		return "ERROR_KIND_CANCELED"
	case 12:
		return "ERROR_KIND_UNAVAILABLE"
	case 13:
		return "ERROR_KIND_INVALID_RESPONSE"
	case 14:
		return "ERROR_KIND_INTERNAL"
	case 15:
		return "ERROR_KIND_FAILED_PRECONDITION"
	default:
		return "UNKNOWN"
	}
}

// CreateOptions is the creation request. It does not include lifecycle
// operations or credentials.
// Omitted fields use provider defaults. A provider rejects settings it cannot
// honor.
//
// Example:
//
//	options := &CreateOptions{
//	    Resources: &Resources{CPUCores: Value(0.5), MemoryMiB: Value(uint64(512))},
//	}
type CreateOptions struct {
	// Name is an optional display name. Nil uses the provider default. An explicit
	// empty string asks for an unnamed sandbox.
	Name *string `json:"name,omitempty" validate:"omitnil"`
	// Source selects an image, snapshot, warm pool, or the provider default. Nil
	// means the provider default.
	Source *SandboxSource `json:"source,omitempty" validate:"omitnil"`
	// Runtime sets language, user, working directory, and entrypoint hints.
	Runtime *RuntimeConfig `json:"runtime,omitempty" validate:"omitnil"`
	// Isolation selects the isolation class, such as a container or Linux VM.
	Isolation *IsolationConfig `json:"isolation,omitempty" validate:"omitnil"`
	// Resources sets CPU, memory, and disk. Units are physical cores and MiB.
	Resources *Resources `json:"resources,omitempty" validate:"omitnil"`
	// Placement sets cloud and region preferences. A preference is not a
	// scheduling guarantee.
	Placement *Placement `json:"placement,omitempty" validate:"omitnil"`
	// Environment is the process environment. An empty map is explicit; nil means
	// omitted.
	Environment map[string]string `json:"environment" validate:""`
	// Labels is caller-supplied labels or tags. An empty map is explicit; nil
	// means omitted.
	Labels map[string]string `json:"labels" validate:""`
	// Network sets egress, allowlists, ports, and related network options.
	Network *NetworkConfig `json:"network,omitempty" validate:"omitnil"`
	// Security sets public access, workload identity, and secret references.
	Security *SecurityConfig `json:"security,omitempty" validate:"omitnil"`
	// Lifetime sets lifetime and idle policies requested at creation. These are
	// not stop or delete calls.
	Lifetime *LifetimePolicy `json:"lifetime,omitempty" validate:"omitnil"`
	// Provisioning sets the creation deadline, queue timeout, and wait condition.
	// JSON name is "creation".
	Provisioning  *ProvisioningOptions `json:"creation,omitempty" validate:"omitnil"`
	Readiness     *ReadinessProbe      `json:"readiness,omitempty" validate:"omitnil"`
	Observability *ObservabilityConfig `json:"observability,omitempty" validate:"omitnil"`
	// ProviderOptions holds provider-specific declarative options. It is never an
	// SDK object or an auth credential.
	ProviderOptions map[string]any `json:"provider_options,omitempty" validate:"omitnil"`
}

// GetName returns Name when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *CreateOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}

// GetSource returns Source when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateOptions) GetSource() *SandboxSource {
	if x != nil {
		return x.Source
	}
	var zero *SandboxSource
	return zero
}

// GetRuntime returns Runtime when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateOptions) GetRuntime() *RuntimeConfig {
	if x != nil {
		return x.Runtime
	}
	var zero *RuntimeConfig
	return zero
}

// GetIsolation returns Isolation when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetIsolation() *IsolationConfig {
	if x != nil {
		return x.Isolation
	}
	var zero *IsolationConfig
	return zero
}

// GetResources returns Resources when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	var zero *Resources
	return zero
}

// GetPlacement returns Placement when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	var zero *Placement
	return zero
}

// GetEnvironment returns Environment when the receiver and field are present.
// A nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	var zero map[string]string
	return zero
}

// GetLabels returns Labels when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateOptions) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	var zero map[string]string
	return zero
}

// GetNetwork returns Network when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateOptions) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	var zero *NetworkConfig
	return zero
}

// GetSecurity returns Security when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateOptions) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	var zero *SecurityConfig
	return zero
}

// GetLifetime returns Lifetime when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateOptions) GetLifetime() *LifetimePolicy {
	if x != nil {
		return x.Lifetime
	}
	var zero *LifetimePolicy
	return zero
}

// GetProvisioning returns Provisioning when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetProvisioning() *ProvisioningOptions {
	if x != nil {
		return x.Provisioning
	}
	var zero *ProvisioningOptions
	return zero
}

// GetReadiness returns Readiness when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetReadiness() *ReadinessProbe {
	if x != nil {
		return x.Readiness
	}
	var zero *ReadinessProbe
	return zero
}

// GetObservability returns Observability when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetObservability() *ObservabilityConfig {
	if x != nil {
		return x.Observability
	}
	var zero *ObservabilityConfig
	return zero
}

// GetProviderOptions returns ProviderOptions when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *CreateOptions) GetProviderOptions() map[string]any {
	if x != nil {
		return x.ProviderOptions
	}
	var zero map[string]any
	return zero
}

// SandboxSource is the sandbox source. Set one alternative. Nil means the
// provider default, which need not be an image.
type SandboxSource struct {
	ProviderDefault *ProviderDefaultSource `json:"provider_default,omitempty" validate:"omitnil"`
	Image           *ImageSource           `json:"image,omitempty" validate:"omitnil"`
	Snapshot        *SnapshotSource        `json:"snapshot,omitempty" validate:"omitnil"`
	WarmPool        *WarmPoolSource        `json:"warm_pool,omitempty" validate:"omitnil"`
}

// GetProviderDefault returns ProviderDefault when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *SandboxSource) GetProviderDefault() *ProviderDefaultSource {
	if x != nil {
		return x.ProviderDefault
	}
	var zero *ProviderDefaultSource
	return zero
}

// GetImage returns Image when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxSource) GetImage() *ImageSource {
	if x != nil {
		return x.Image
	}
	var zero *ImageSource
	return zero
}

// GetSnapshot returns Snapshot when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxSource) GetSnapshot() *SnapshotSource {
	if x != nil {
		return x.Snapshot
	}
	var zero *SnapshotSource
	return zero
}

// GetWarmPool returns WarmPool when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxSource) GetWarmPool() *WarmPoolSource {
	if x != nil {
		return x.WarmPool
	}
	var zero *WarmPoolSource
	return zero
}

// ProviderDefaultSource asks the provider to choose its default source.
type ProviderDefaultSource struct {
}

// ImageSource is a container image reference, such as "alpine:3.21".
type ImageSource struct {
	// Reference is the registry image reference.
	Reference string `json:"reference,omitempty" validate:"nonblank"`
}

// GetReference returns Reference when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *ImageSource) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}

// SnapshotSource is an existing snapshot. Reference identifies it. Kind
// classifies it.
type SnapshotSource struct {
	// Reference is the provider snapshot identifier.
	Reference string `json:"reference,omitempty" validate:"nonblank"`
	// Kind classifies the snapshot. Default leaves the class to the provider.
	Kind SnapshotKind `json:"kind,omitempty" validate:""`
	// ProviderKind is a provider-specific kind name when Kind is
	// provider-specific.
	ProviderKind *string `json:"provider_kind,omitempty" validate:"omitnil"`
}

// GetReference returns Reference when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *SnapshotSource) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}

// GetKind returns Kind when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *SnapshotSource) GetKind() SnapshotKind {
	if x != nil {
		return x.Kind
	}
	var zero SnapshotKind
	return zero
}

// GetProviderKind returns ProviderKind when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *SnapshotSource) GetProviderKind() string {
	if x != nil && x.ProviderKind != nil {
		return *x.ProviderKind
	}
	var zero string
	return zero
}

// WarmPoolSource is an existing warm pool. Reference identifies it.
type WarmPoolSource struct {
	// Reference is the provider warm-pool identifier.
	Reference string `json:"reference,omitempty" validate:"nonblank"`
}

// GetReference returns Reference when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *WarmPoolSource) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}

// RuntimeConfig is process setup applied when the sandbox starts. Language is
// a hint, not an install promise.
type RuntimeConfig struct {
	// Language is a language or toolbox hint. It does not promise that a runtime
	// is installed.
	Language         *string  `json:"language,omitempty" validate:"omitnil,nonblank"`
	Version          *string  `json:"version,omitempty" validate:"omitnil,nonblank"`
	User             *string  `json:"user,omitempty" validate:"omitnil,nonblank"`
	WorkingDirectory *string  `json:"working_directory,omitempty" validate:"omitnil,nonblank"`
	Entrypoint       []string `json:"entrypoint" validate:"dive,nonblank"`
	PTY              *bool    `json:"pty,omitempty" validate:"omitnil"`
}

// GetLanguage returns Language when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *RuntimeConfig) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	var zero string
	return zero
}

// GetVersion returns Version when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *RuntimeConfig) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	var zero string
	return zero
}

// GetUser returns User when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *RuntimeConfig) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	var zero string
	return zero
}

// GetWorkingDirectory returns WorkingDirectory when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *RuntimeConfig) GetWorkingDirectory() string {
	if x != nil && x.WorkingDirectory != nil {
		return *x.WorkingDirectory
	}
	var zero string
	return zero
}

// GetEntrypoint returns Entrypoint when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *RuntimeConfig) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	var zero []string
	return zero
}

// GetPTY returns PTY when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *RuntimeConfig) GetPTY() bool {
	if x != nil && x.PTY != nil {
		return *x.PTY
	}
	var zero bool
	return zero
}

// IsolationConfig selects how the sandbox is isolated. Kind default leaves the
// class to the provider.
type IsolationConfig struct {
	Kind                 IsolationKind `json:"kind,omitempty" validate:""`
	ProviderKind         *string       `json:"provider_kind,omitempty" validate:"omitnil"`
	NestedVirtualization *bool         `json:"nested_virtualization,omitempty" validate:"omitnil"`
}

// GetKind returns Kind when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *IsolationConfig) GetKind() IsolationKind {
	if x != nil {
		return x.Kind
	}
	var zero IsolationKind
	return zero
}

// GetProviderKind returns ProviderKind when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *IsolationConfig) GetProviderKind() string {
	if x != nil && x.ProviderKind != nil {
		return *x.ProviderKind
	}
	var zero string
	return zero
}

// GetNestedVirtualization returns NestedVirtualization when the receiver and
// field are present. A nil receiver or omitted field returns the zero value.
func (x *IsolationConfig) GetNestedVirtualization() bool {
	if x != nil && x.NestedVirtualization != nil {
		return *x.NestedVirtualization
	}
	var zero bool
	return zero
}

// Resources is the requested compute size. Omitted fields use provider
// defaults.
// GPU requests and resizing are not creation settings.
type Resources struct {
	// CPUCores is the requested physical CPU count. Modal allows fractions.
	// Daytona requires whole cores.
	CPUCores *float64 `json:"cpu_cores,omitempty" validate:"omitnil,finite,gt=0"`
	// CPULimitCores is an optional CPU ceiling. A positive limit requires a
	// request and cannot be smaller than it.
	CPULimitCores *float64 `json:"cpu_limit_cores,omitempty" validate:"omitnil,finite,gte=0"`
	// MemoryMiB is requested memory in MiB. Providers convert this to the native
	// unit.
	MemoryMiB *uint64 `json:"memory_mib,omitempty" validate:"omitnil,gt=0"`
	// MemoryLimitMiB is an optional memory ceiling in MiB. A positive limit
	// requires a request.
	MemoryLimitMiB *uint64 `json:"memory_limit_mib,omitempty" validate:"omitnil"`
	// DiskMiB is requested disk in MiB. Modal rejects a creation override. Daytona
	// requires whole GiB.
	DiskMiB *uint64 `json:"disk_mib,omitempty" validate:"omitnil,gt=0"`
}

// GetCPUCores returns CPUCores when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Resources) GetCPUCores() float64 {
	if x != nil && x.CPUCores != nil {
		return *x.CPUCores
	}
	var zero float64
	return zero
}

// GetCPULimitCores returns CPULimitCores when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *Resources) GetCPULimitCores() float64 {
	if x != nil && x.CPULimitCores != nil {
		return *x.CPULimitCores
	}
	var zero float64
	return zero
}

// GetMemoryMiB returns MemoryMiB when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *Resources) GetMemoryMiB() uint64 {
	if x != nil && x.MemoryMiB != nil {
		return *x.MemoryMiB
	}
	var zero uint64
	return zero
}

// GetMemoryLimitMiB returns MemoryLimitMiB when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *Resources) GetMemoryLimitMiB() uint64 {
	if x != nil && x.MemoryLimitMiB != nil {
		return *x.MemoryLimitMiB
	}
	var zero uint64
	return zero
}

// GetDiskMiB returns DiskMiB when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Resources) GetDiskMiB() uint64 {
	if x != nil && x.DiskMiB != nil {
		return *x.DiskMiB
	}
	var zero uint64
	return zero
}

// Placement is a placement preference. The provider may still choose another
// location.
type Placement struct {
	// Cloud is a cloud name such as aws, gcp, or oci. Supported names depend on
	// the provider.
	Cloud *string `json:"cloud,omitempty" validate:"omitnil"`
	// Regions lists region preferences in order. It does not promise multi-region
	// support.
	Regions []string `json:"regions" validate:"dive,nonblank"`
	// Target is a provider target. Daytona maps the client region here.
	// Per-request placement is unsupported.
	Target *string `json:"target,omitempty" validate:"omitnil"`
}

// GetCloud returns Cloud when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Placement) GetCloud() string {
	if x != nil && x.Cloud != nil {
		return *x.Cloud
	}
	var zero string
	return zero
}

// GetRegions returns Regions when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Placement) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	var zero []string
	return zero
}

// GetTarget returns Target when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *Placement) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	var zero string
	return zero
}

// StringAllowlist is an allowlist. A present empty list means deny all. Nil
// means the list was omitted.
type StringAllowlist struct {
	// Entries lists allowed values. A present empty list means deny all. Nil means
	// the list was omitted.
	Entries []string `json:"entries" validate:""`
}

// GetEntries returns Entries when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *StringAllowlist) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	var zero []string
	return zero
}

// NetworkConfig is creation-time networking. Empty allowlists do not mean the
// same thing as omitted ones.
type NetworkConfig struct {
	// Egress selects the outbound policy. Default leaves it to the provider.
	Egress EgressMode `json:"egress,omitempty" validate:""`
	// OutboundCIDRs limits outbound traffic to these CIDR ranges.
	OutboundCIDRs *StringAllowlist `json:"outbound_cidrs,omitempty" validate:"omitnil"`
	// OutboundDomains limits outbound traffic to these domains.
	OutboundDomains *StringAllowlist `json:"outbound_domains,omitempty" validate:"omitnil"`
	// InboundCIDRs limits inbound traffic to these CIDR ranges.
	InboundCIDRs *StringAllowlist `json:"inbound_cidrs,omitempty" validate:"omitnil"`
	// PrivateNetwork asks for a private network when the provider supports one.
	PrivateNetwork *bool `json:"private_network,omitempty" validate:"omitnil"`
	// LinkedSandbox names another sandbox to link. The provider must already know
	// that sandbox.
	LinkedSandbox *string `json:"linked_sandbox,omitempty" validate:"omitnil"`
	// ProxyReference names a provider-managed proxy.
	ProxyReference *string `json:"proxy_reference,omitempty" validate:"omitnil"`
	// OutboundProxyURL is an outbound proxy URL.
	OutboundProxyURL *string `json:"outbound_proxy_url,omitempty" validate:"omitnil"`
	// CustomDomain is a custom domain for the sandbox, when the provider supports
	// one.
	CustomDomain *string `json:"custom_domain,omitempty" validate:"omitnil"`
	// Ports publishes these ports.
	Ports []*PortBinding `json:"ports" validate:"dive,required"`
}

// GetEgress returns Egress when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetEgress() EgressMode {
	if x != nil {
		return x.Egress
	}
	var zero EgressMode
	return zero
}

// GetOutboundCIDRs returns OutboundCIDRs when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetOutboundCIDRs() *StringAllowlist {
	if x != nil {
		return x.OutboundCIDRs
	}
	var zero *StringAllowlist
	return zero
}

// GetOutboundDomains returns OutboundDomains when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetOutboundDomains() *StringAllowlist {
	if x != nil {
		return x.OutboundDomains
	}
	var zero *StringAllowlist
	return zero
}

// GetInboundCIDRs returns InboundCIDRs when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetInboundCIDRs() *StringAllowlist {
	if x != nil {
		return x.InboundCIDRs
	}
	var zero *StringAllowlist
	return zero
}

// GetPrivateNetwork returns PrivateNetwork when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetPrivateNetwork() bool {
	if x != nil && x.PrivateNetwork != nil {
		return *x.PrivateNetwork
	}
	var zero bool
	return zero
}

// GetLinkedSandbox returns LinkedSandbox when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetLinkedSandbox() string {
	if x != nil && x.LinkedSandbox != nil {
		return *x.LinkedSandbox
	}
	var zero string
	return zero
}

// GetProxyReference returns ProxyReference when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetProxyReference() string {
	if x != nil && x.ProxyReference != nil {
		return *x.ProxyReference
	}
	var zero string
	return zero
}

// GetOutboundProxyURL returns OutboundProxyURL when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetOutboundProxyURL() string {
	if x != nil && x.OutboundProxyURL != nil {
		return *x.OutboundProxyURL
	}
	var zero string
	return zero
}

// GetCustomDomain returns CustomDomain when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetCustomDomain() string {
	if x != nil && x.CustomDomain != nil {
		return *x.CustomDomain
	}
	var zero string
	return zero
}

// GetPorts returns Ports when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *NetworkConfig) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	var zero []*PortBinding
	return zero
}

// PortBinding publishes one port. Port is the container port. Transport
// selects the protocol.
type PortBinding struct {
	// Port is the port number to publish.
	Port uint32 `json:"port,omitempty" validate:"gte=1,lte=65535"`
	// Transport selects TLS, HTTP/2, or plain transport. Default leaves the choice
	// to the provider.
	Transport PortTransport `json:"transport,omitempty" validate:""`
}

// GetPort returns Port when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *PortBinding) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	var zero uint32
	return zero
}

// GetTransport returns Transport when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *PortBinding) GetTransport() PortTransport {
	if x != nil {
		return x.Transport
	}
	var zero PortTransport
	return zero
}

// SecurityConfig sets access and secret references. Secrets are
// provider-managed names, not credential values.
type SecurityConfig struct {
	// PublicAccess requests public access when true. Nil leaves the provider
	// default.
	PublicAccess *bool `json:"public_access,omitempty" validate:"omitnil"`
	// WorkloadIdentity requests a workload identity when the provider supports
	// one.
	WorkloadIdentity *bool `json:"workload_identity,omitempty" validate:"omitnil"`
	// Secrets names provider-managed secrets. These are not credential values.
	Secrets []*SecretReference `json:"secrets" validate:"dive,required"`
}

// GetPublicAccess returns PublicAccess when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *SecurityConfig) GetPublicAccess() bool {
	if x != nil && x.PublicAccess != nil {
		return *x.PublicAccess
	}
	var zero bool
	return zero
}

// GetWorkloadIdentity returns WorkloadIdentity when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *SecurityConfig) GetWorkloadIdentity() bool {
	if x != nil && x.WorkloadIdentity != nil {
		return *x.WorkloadIdentity
	}
	var zero bool
	return zero
}

// GetSecrets returns Secrets when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SecurityConfig) GetSecrets() []*SecretReference {
	if x != nil {
		return x.Secrets
	}
	var zero []*SecretReference
	return zero
}

// SecretReference names a provider-managed secret and how it is injected.
type SecretReference struct {
	// Reference is the provider secret name.
	Reference string `json:"reference,omitempty" validate:"nonblank"`
	// EnvironmentVariable is the environment variable that receives the secret,
	// when injection uses the environment.
	EnvironmentVariable *string `json:"environment_variable,omitempty" validate:"omitnil,nonblank"`
	// Injection selects environment injection or an egress placeholder.
	Injection SecretInjection `json:"injection,omitempty" validate:""`
}

// GetReference returns Reference when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *SecretReference) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}

// GetEnvironmentVariable returns EnvironmentVariable when the receiver and
// field are present. A nil receiver or omitted field returns the zero value.
func (x *SecretReference) GetEnvironmentVariable() string {
	if x != nil && x.EnvironmentVariable != nil {
		return *x.EnvironmentVariable
	}
	var zero string
	return zero
}

// GetInjection returns Injection when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *SecretReference) GetInjection() SecretInjection {
	if x != nil {
		return x.Injection
	}
	var zero SecretInjection
	return zero
}

// LifetimePolicy is requested at creation. It is not a stop, pause, or delete
// call.
type LifetimePolicy struct {
	// MaximumLifetime is the maximum lifetime. Nil uses the provider default.
	// Explicit zero means unlimited when the provider supports that.
	MaximumLifetime *time.Duration `json:"maximum_lifetime,omitempty" validate:"omitnil,gte=0"`
	// Ephemeral requests deletion when the sandbox stops, where the provider
	// supports it.
	Ephemeral *bool `json:"ephemeral,omitempty" validate:"omitnil"`
	// IdleTerminate ends the sandbox after it is idle.
	IdleTerminate *AutomaticAction `json:"idle_terminate,omitempty" validate:"omitnil"`
	// IdleStop stops the sandbox after it is idle. Daytona maps a disabled stop to
	// native zero.
	IdleStop *AutomaticAction `json:"idle_stop,omitempty" validate:"omitnil"`
	// IdlePause pauses the sandbox after it is idle. A positive delay conflicts
	// with a positive stop delay.
	IdlePause *AutomaticAction `json:"idle_pause,omitempty" validate:"omitnil"`
	// StoppedArchive archives a stopped sandbox after a delay. Daytona rejects
	// disable and immediate archive.
	StoppedArchive *AutomaticAction `json:"stopped_archive,omitempty" validate:"omitnil"`
	// StoppedDelete deletes a stopped sandbox. Daytona maps immediate delete to
	// native zero.
	StoppedDelete *AutomaticAction `json:"stopped_delete,omitempty" validate:"omitnil"`
}

// GetMaximumLifetime returns MaximumLifetime when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetMaximumLifetime() *time.Duration {
	if x != nil {
		return x.MaximumLifetime
	}
	var zero *time.Duration
	return zero
}

// GetEphemeral returns Ephemeral when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetEphemeral() bool {
	if x != nil && x.Ephemeral != nil {
		return *x.Ephemeral
	}
	var zero bool
	return zero
}

// GetIdleTerminate returns IdleTerminate when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetIdleTerminate() *AutomaticAction {
	if x != nil {
		return x.IdleTerminate
	}
	var zero *AutomaticAction
	return zero
}

// GetIdleStop returns IdleStop when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetIdleStop() *AutomaticAction {
	if x != nil {
		return x.IdleStop
	}
	var zero *AutomaticAction
	return zero
}

// GetIdlePause returns IdlePause when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetIdlePause() *AutomaticAction {
	if x != nil {
		return x.IdlePause
	}
	var zero *AutomaticAction
	return zero
}

// GetStoppedArchive returns StoppedArchive when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetStoppedArchive() *AutomaticAction {
	if x != nil {
		return x.StoppedArchive
	}
	var zero *AutomaticAction
	return zero
}

// GetStoppedDelete returns StoppedDelete when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *LifetimePolicy) GetStoppedDelete() *AutomaticAction {
	if x != nil {
		return x.StoppedDelete
	}
	var zero *AutomaticAction
	return zero
}

// AutomaticAction is one idle or stopped policy. Disabled, immediate, and
// delayed do not share one zero value.
type AutomaticAction struct {
	// Mode is default, disabled, or after a delay. Default omits the policy.
	Mode PolicyMode `json:"mode,omitempty" validate:"gte=0,lte=2"`
	// After is the delay used when Mode is after. Zero means immediate, not
	// disabled.
	After *time.Duration `json:"after,omitempty" validate:"omitnil,gte=0"`
}

// GetMode returns Mode when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *AutomaticAction) GetMode() PolicyMode {
	if x != nil {
		return x.Mode
	}
	var zero PolicyMode
	return zero
}

// GetAfter returns After when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *AutomaticAction) GetAfter() *time.Duration {
	if x != nil {
		return x.After
	}
	var zero *time.Duration
	return zero
}

// ProvisioningOptions is creation waiting, separate from sandbox lifetime.
type ProvisioningOptions struct {
	// Timeout is the client operation deadline, distinct from sandbox lifetime and
	// queue time.
	// Nil and explicit zero add no Kit deadline.
	Timeout *time.Duration `json:"timeout,omitempty" validate:"omitnil,gte=0"`
	// QueueTimeout is how long creation may wait in a provider queue. It is not
	// the sandbox lifetime.
	QueueTimeout *time.Duration `json:"queue_timeout,omitempty" validate:"omitnil,gte=0"`
	// WaitFor is the condition creation waits for before it returns.
	WaitFor WaitCondition `json:"wait_for,omitempty" validate:""`
}

// GetTimeout returns Timeout when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ProvisioningOptions) GetTimeout() *time.Duration {
	if x != nil {
		return x.Timeout
	}
	var zero *time.Duration
	return zero
}

// GetQueueTimeout returns QueueTimeout when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *ProvisioningOptions) GetQueueTimeout() *time.Duration {
	if x != nil {
		return x.QueueTimeout
	}
	var zero *time.Duration
	return zero
}

// GetWaitFor returns WaitFor when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ProvisioningOptions) GetWaitFor() WaitCondition {
	if x != nil {
		return x.WaitFor
	}
	var zero WaitCondition
	return zero
}

// ReadinessProbe is the check used when waiting until ready. Set either a TCP
// port or a command.
type ReadinessProbe struct {
	TCPPort *uint32       `json:"tcp_port,omitempty" validate:"omitnil,gte=1,lte=65535"`
	Command *CommandProbe `json:"command,omitempty" validate:"omitnil"`
}

// GetTCPPort returns TCPPort when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ReadinessProbe) GetTCPPort() uint32 {
	if x != nil && x.TCPPort != nil {
		return *x.TCPPort
	}
	var zero uint32
	return zero
}

// GetCommand returns Command when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ReadinessProbe) GetCommand() *CommandProbe {
	if x != nil {
		return x.Command
	}
	var zero *CommandProbe
	return zero
}

// CommandProbe is a command readiness check. Argv is the command and its
// arguments.
type CommandProbe struct {
	Argv []string `json:"argv" validate:"min=1"`
}

// GetArgv returns Argv when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *CommandProbe) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	var zero []string
	return zero
}

// ObservabilityConfig sets provider logging and telemetry options.
type ObservabilityConfig struct {
	Verbose           *bool   `json:"verbose,omitempty" validate:"omitnil"`
	TelemetryEndpoint *string `json:"telemetry_endpoint,omitempty" validate:"omitnil,nonblank"`
}

// GetVerbose returns Verbose when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ObservabilityConfig) GetVerbose() bool {
	if x != nil && x.Verbose != nil {
		return *x.Verbose
	}
	var zero bool
	return zero
}

// GetTelemetryEndpoint returns TelemetryEndpoint when the receiver and field
// are present. A nil receiver or omitted field returns the zero value.
func (x *ObservabilityConfig) GetTelemetryEndpoint() string {
	if x != nil && x.TelemetryEndpoint != nil {
		return *x.TelemetryEndpoint
	}
	var zero string
	return zero
}

// CreateResult is the metadata returned by a provider create call.
type CreateResult struct {
	// Sandbox is the created sandbox. ID must be present before a public handle is
	// built.
	Sandbox *SandboxInfo `json:"sandbox,omitempty" validate:"omitnil"`
}

// GetSandbox returns Sandbox when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *CreateResult) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	var zero *SandboxInfo
	return zero
}

// SandboxInfo is shared metadata. Optional fields stay absent when the
// provider did not report them.
//
// Example:
//
//	info := instance.Info()
//	fmt.Println(info.GetID(), info.Origins[InfoFieldName])
type SandboxInfo struct {
	// ID is the provider sandbox identifier. Creation fails locally when it is
	// empty.
	ID string `json:"id,omitempty" validate:""`
	// Provider is the selected provider identifier.
	Provider string `json:"provider,omitempty" validate:""`
	// Name is the sandbox name when one is known. Nil means it was not reported.
	Name *string `json:"name,omitempty" validate:"omitnil"`
	// ProviderState is the provider's own state string. It is not a shared
	// lifecycle state machine.
	ProviderState    *string           `json:"provider_state,omitempty" validate:"omitnil"`
	Region           *string           `json:"region,omitempty" validate:"omitnil"`
	Isolation        *IsolationConfig  `json:"isolation,omitempty" validate:"omitnil"`
	Resources        *Resources        `json:"resources,omitempty" validate:"omitnil"`
	Labels           map[string]string `json:"labels" validate:""`
	CreatedAt        *time.Time        `json:"created_at,omitempty" validate:"omitnil"`
	ProviderMetadata map[string]any    `json:"provider_metadata,omitempty" validate:"omitnil"`
	// Origins records where each present field came from. A missing entry means
	// the origin is unknown.
	Origins map[string]ValueOrigin `json:"origins" validate:""`
}

// GetID returns ID when the receiver and field are present. A nil receiver or
// omitted field returns the zero value.
func (x *SandboxInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	var zero string
	return zero
}

// GetProvider returns Provider when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	var zero string
	return zero
}

// GetName returns Name when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *SandboxInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}

// GetProviderState returns ProviderState when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetProviderState() string {
	if x != nil && x.ProviderState != nil {
		return *x.ProviderState
	}
	var zero string
	return zero
}

// GetRegion returns Region when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	var zero string
	return zero
}

// GetIsolation returns Isolation when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetIsolation() *IsolationConfig {
	if x != nil {
		return x.Isolation
	}
	var zero *IsolationConfig
	return zero
}

// GetResources returns Resources when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	var zero *Resources
	return zero
}

// GetLabels returns Labels when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	var zero map[string]string
	return zero
}

// GetCreatedAt returns CreatedAt when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetCreatedAt() *time.Time {
	if x != nil {
		return x.CreatedAt
	}
	var zero *time.Time
	return zero
}

// GetProviderMetadata returns ProviderMetadata when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetProviderMetadata() map[string]any {
	if x != nil {
		return x.ProviderMetadata
	}
	var zero map[string]any
	return zero
}

// GetOrigins returns Origins when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *SandboxInfo) GetOrigins() map[string]ValueOrigin {
	if x != nil {
		return x.Origins
	}
	var zero map[string]ValueOrigin
	return zero
}

// ErrorInfo is the portable error detail. The native cause stays on the
// runtime error and is not serialized.
// Unknown classifications do not imply that a retry is safe.
//
// Example:
//
//	err := NewError(ErrorInfo{
//	    Kind:    ErrorKindUnsupported,
//	    Field:   CreateFieldResourcesDiskMiB,
//	    Message: "disk overrides are unsupported",
//	}, cause)
type ErrorInfo struct {
	// Kind is the shared category, such as invalid argument or unsupported.
	Kind ErrorKind `json:"kind,omitempty" validate:""`
	// Provider is the provider identifier, such as "modal" or "daytona". Empty
	// when the failure is local.
	Provider string `json:"provider,omitempty" validate:""`
	// Operation is the Kit operation, such as "create", "initialize", or "close".
	Operation string `json:"operation,omitempty" validate:""`
	// Field is the canonical field path involved, such as "resources.cpu_cores".
	// Empty when no field applies.
	Field string `json:"field,omitempty" validate:""`
	// Message is the human-readable explanation.
	Message string `json:"message,omitempty" validate:""`
	// StatusCode is the native HTTP or transport status when the provider reported
	// one.
	StatusCode *uint32 `json:"status_code,omitempty" validate:"omitnil"`
	// ProviderCode is the provider's own error code when one was reported.
	ProviderCode *string `json:"provider_code,omitempty" validate:"omitnil"`
	// ProviderSource is the provider component that reported the error, when
	// available.
	ProviderSource *string `json:"provider_source,omitempty" validate:"omitnil"`
}

// GetKind returns Kind when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *ErrorInfo) GetKind() ErrorKind {
	if x != nil {
		return x.Kind
	}
	var zero ErrorKind
	return zero
}

// GetProvider returns Provider when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	var zero string
	return zero
}

// GetOperation returns Operation when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	var zero string
	return zero
}

// GetField returns Field when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetField() string {
	if x != nil {
		return x.Field
	}
	var zero string
	return zero
}

// GetMessage returns Message when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	var zero string
	return zero
}

// GetStatusCode returns StatusCode when the receiver and field are present. A
// nil receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetStatusCode() uint32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	var zero uint32
	return zero
}

// GetProviderCode returns ProviderCode when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetProviderCode() string {
	if x != nil && x.ProviderCode != nil {
		return *x.ProviderCode
	}
	var zero string
	return zero
}

// GetProviderSource returns ProviderSource when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *ErrorInfo) GetProviderSource() string {
	if x != nil && x.ProviderSource != nil {
		return *x.ProviderSource
	}
	var zero string
	return zero
}

// MetadataValue Exact numeric alternatives avoid protobuf Struct's double-only
// representation.
// An empty value represents null.
type MetadataValue struct {
	Boolean         *bool          `json:"boolean,omitempty" validate:"omitnil"`
	Text            *string        `json:"text,omitempty" validate:"omitnil"`
	SignedInteger   *int64         `json:"signed_integer,omitempty" validate:"omitnil"`
	UnsignedInteger *uint64        `json:"unsigned_integer,omitempty" validate:"omitnil"`
	Number          *float64       `json:"number,omitempty" validate:"omitnil"`
	Binary          *[]byte        `json:"binary,omitempty" validate:"omitnil"`
	List            *MetadataList  `json:"list,omitempty" validate:"omitnil"`
	Object          map[string]any `json:"object,omitempty" validate:"omitnil"`
}

// GetBoolean returns Boolean when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *MetadataValue) GetBoolean() bool {
	if x != nil && x.Boolean != nil {
		return *x.Boolean
	}
	var zero bool
	return zero
}

// GetText returns Text when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *MetadataValue) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	var zero string
	return zero
}

// GetSignedInteger returns SignedInteger when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *MetadataValue) GetSignedInteger() int64 {
	if x != nil && x.SignedInteger != nil {
		return *x.SignedInteger
	}
	var zero int64
	return zero
}

// GetUnsignedInteger returns UnsignedInteger when the receiver and field are
// present. A nil receiver or omitted field returns the zero value.
func (x *MetadataValue) GetUnsignedInteger() uint64 {
	if x != nil && x.UnsignedInteger != nil {
		return *x.UnsignedInteger
	}
	var zero uint64
	return zero
}

// GetNumber returns Number when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *MetadataValue) GetNumber() float64 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	var zero float64
	return zero
}

// GetBinary returns Binary when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *MetadataValue) GetBinary() []byte {
	if x != nil && x.Binary != nil {
		return *x.Binary
	}
	var zero []byte
	return zero
}

// GetList returns List when the receiver and field are present. A nil receiver
// or omitted field returns the zero value.
func (x *MetadataValue) GetList() *MetadataList {
	if x != nil {
		return x.List
	}
	var zero *MetadataList
	return zero
}

// GetObject returns Object when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *MetadataValue) GetObject() map[string]any {
	if x != nil {
		return x.Object
	}
	var zero map[string]any
	return zero
}

// MetadataList is an ordered list of metadata values.
type MetadataList struct {
	// Values is the list contents. An empty list is explicit.
	Values []*MetadataValue `json:"values" validate:"dive,required"`
}

// GetValues returns Values when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *MetadataList) GetValues() []*MetadataValue {
	if x != nil {
		return x.Values
	}
	var zero []*MetadataValue
	return zero
}

// MetadataObject is a string-keyed metadata object. Go exposes this as
// map[string]any.
type MetadataObject struct {
	// Values is the object contents. An empty object is explicit.
	Values map[string]*MetadataValue `json:"values" validate:""`
}

// GetValues returns Values when the receiver and field are present. A nil
// receiver or omitted field returns the zero value.
func (x *MetadataObject) GetValues() map[string]*MetadataValue {
	if x != nil {
		return x.Values
	}
	var zero map[string]*MetadataValue
	return zero
}

// Value marks an optional scalar as explicitly supplied, including zero and
// false.
// It does not validate the value.
//
// Example:
//
//	cores := Value(0.5)
//	disabled := Value(false)
func Value[T any](value T) *T {
	return &value
}
