// Code generated by protoc-gen-kit-go. DO NOT EDIT.
// source: kit/sandbox/v1/sandbox.proto
package sandbox

import (
	time "time"
)

type SnapshotKind int32

const (
	SnapshotKindDefault          SnapshotKind = 0
	SnapshotKindFilesystem       SnapshotKind = 1
	SnapshotKindMemory           SnapshotKind = 2
	SnapshotKindImage            SnapshotKind = 3
	SnapshotKindMachine          SnapshotKind = 4
	SnapshotKindCheckpoint       SnapshotKind = 5
	SnapshotKindProviderSpecific SnapshotKind = 6
)

// Valid reports whether the value is declared in the shared schema.
func (x SnapshotKind) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	case 5:
		return true
	case 6:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x SnapshotKind) String() string {
	switch x {
	case 0:
		return "SNAPSHOT_KIND_DEFAULT"
	case 1:
		return "SNAPSHOT_KIND_FILESYSTEM"
	case 2:
		return "SNAPSHOT_KIND_MEMORY"
	case 3:
		return "SNAPSHOT_KIND_IMAGE"
	case 4:
		return "SNAPSHOT_KIND_MACHINE"
	case 5:
		return "SNAPSHOT_KIND_CHECKPOINT"
	case 6:
		return "SNAPSHOT_KIND_PROVIDER_SPECIFIC"
	default:
		return "UNKNOWN"
	}
}

type IsolationKind int32

const (
	IsolationKindDefault          IsolationKind = 0
	IsolationKindContainer        IsolationKind = 1
	IsolationKindMicroVM          IsolationKind = 2
	IsolationKindLinuxVM          IsolationKind = 3
	IsolationKindWorker           IsolationKind = 4
	IsolationKindProviderSpecific IsolationKind = 5
)

// Valid reports whether the value is declared in the shared schema.
func (x IsolationKind) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	case 5:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x IsolationKind) String() string {
	switch x {
	case 0:
		return "ISOLATION_KIND_DEFAULT"
	case 1:
		return "ISOLATION_KIND_CONTAINER"
	case 2:
		return "ISOLATION_KIND_MICROVM"
	case 3:
		return "ISOLATION_KIND_LINUX_VM"
	case 4:
		return "ISOLATION_KIND_WORKER"
	case 5:
		return "ISOLATION_KIND_PROVIDER_SPECIFIC"
	default:
		return "UNKNOWN"
	}
}

type EgressMode int32

const (
	EgressModeDefault    EgressMode = 0
	EgressModeAllowAll   EgressMode = 1
	EgressModeBlockAll   EgressMode = 2
	EgressModeRestricted EgressMode = 3
)

// Valid reports whether the value is declared in the shared schema.
func (x EgressMode) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x EgressMode) String() string {
	switch x {
	case 0:
		return "EGRESS_MODE_DEFAULT"
	case 1:
		return "EGRESS_MODE_ALLOW_ALL"
	case 2:
		return "EGRESS_MODE_BLOCK_ALL"
	case 3:
		return "EGRESS_MODE_RESTRICTED"
	default:
		return "UNKNOWN"
	}
}

type PortTransport int32

const (
	PortTransportDefault  PortTransport = 0
	PortTransportTLS      PortTransport = 1
	PortTransportHTTP2TLS PortTransport = 2
	PortTransportPlain    PortTransport = 3
)

// Valid reports whether the value is declared in the shared schema.
func (x PortTransport) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x PortTransport) String() string {
	switch x {
	case 0:
		return "PORT_TRANSPORT_DEFAULT"
	case 1:
		return "PORT_TRANSPORT_TLS"
	case 2:
		return "PORT_TRANSPORT_HTTP2_TLS"
	case 3:
		return "PORT_TRANSPORT_PLAIN"
	default:
		return "UNKNOWN"
	}
}

type SecretInjection int32

const (
	SecretInjectionDefault           SecretInjection = 0
	SecretInjectionEnvironment       SecretInjection = 1
	SecretInjectionEgressPlaceholder SecretInjection = 2
)

// Valid reports whether the value is declared in the shared schema.
func (x SecretInjection) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x SecretInjection) String() string {
	switch x {
	case 0:
		return "SECRET_INJECTION_DEFAULT"
	case 1:
		return "SECRET_INJECTION_ENVIRONMENT"
	case 2:
		return "SECRET_INJECTION_EGRESS_PLACEHOLDER"
	default:
		return "UNKNOWN"
	}
}

type PolicyMode int32

const (
	PolicyModeDefault  PolicyMode = 0
	PolicyModeDisabled PolicyMode = 1
	PolicyModeAfter    PolicyMode = 2
)

// Valid reports whether the value is declared in the shared schema.
func (x PolicyMode) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x PolicyMode) String() string {
	switch x {
	case 0:
		return "POLICY_MODE_DEFAULT"
	case 1:
		return "POLICY_MODE_DISABLED"
	case 2:
		return "POLICY_MODE_AFTER"
	default:
		return "UNKNOWN"
	}
}

type WaitCondition int32

const (
	WaitConditionDefault   WaitCondition = 0
	WaitConditionSubmitted WaitCondition = 1
	WaitConditionScheduled WaitCondition = 2
	WaitConditionStarted   WaitCondition = 3
	WaitConditionReady     WaitCondition = 4
)

// Valid reports whether the value is declared in the shared schema.
func (x WaitCondition) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x WaitCondition) String() string {
	switch x {
	case 0:
		return "WAIT_CONDITION_DEFAULT"
	case 1:
		return "WAIT_CONDITION_SUBMITTED"
	case 2:
		return "WAIT_CONDITION_SCHEDULED"
	case 3:
		return "WAIT_CONDITION_STARTED"
	case 4:
		return "WAIT_CONDITION_READY"
	default:
		return "UNKNOWN"
	}
}

type ValueOrigin int32

const (
	ValueOriginUnknown  ValueOrigin = 0
	ValueOriginProvider ValueOrigin = 1
	ValueOriginRequest  ValueOrigin = 2
)

// Valid reports whether the value is declared in the shared schema.
func (x ValueOrigin) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x ValueOrigin) String() string {
	switch x {
	case 0:
		return "VALUE_ORIGIN_UNKNOWN"
	case 1:
		return "VALUE_ORIGIN_PROVIDER"
	case 2:
		return "VALUE_ORIGIN_REQUEST"
	default:
		return "UNKNOWN"
	}
}

type ErrorKind int32

const (
	ErrorKindUnknown            ErrorKind = 0
	ErrorKindInvalidArgument    ErrorKind = 1
	ErrorKindUnsupported        ErrorKind = 2
	ErrorKindAuthentication     ErrorKind = 3
	ErrorKindPermissionDenied   ErrorKind = 4
	ErrorKindNotFound           ErrorKind = 5
	ErrorKindAlreadyExists      ErrorKind = 6
	ErrorKindConflict           ErrorKind = 7
	ErrorKindRateLimited        ErrorKind = 8
	ErrorKindResourceExhausted  ErrorKind = 9
	ErrorKindTimeout            ErrorKind = 10
	ErrorKindCanceled           ErrorKind = 11
	ErrorKindUnavailable        ErrorKind = 12
	ErrorKindInvalidResponse    ErrorKind = 13
	ErrorKindInternal           ErrorKind = 14
	ErrorKindFailedPrecondition ErrorKind = 15
)

// Valid reports whether the value is declared in the shared schema.
func (x ErrorKind) Valid() bool {
	switch x {
	case 0:
		return true
	case 1:
		return true
	case 2:
		return true
	case 3:
		return true
	case 4:
		return true
	case 5:
		return true
	case 6:
		return true
	case 7:
		return true
	case 8:
		return true
	case 9:
		return true
	case 10:
		return true
	case 11:
		return true
	case 12:
		return true
	case 13:
		return true
	case 14:
		return true
	case 15:
		return true
	default:
		return false
	}
}

// String returns the stable schema identifier for diagnostics.
func (x ErrorKind) String() string {
	switch x {
	case 0:
		return "ERROR_KIND_UNKNOWN"
	case 1:
		return "ERROR_KIND_INVALID_ARGUMENT"
	case 2:
		return "ERROR_KIND_UNSUPPORTED"
	case 3:
		return "ERROR_KIND_AUTHENTICATION"
	case 4:
		return "ERROR_KIND_PERMISSION_DENIED"
	case 5:
		return "ERROR_KIND_NOT_FOUND"
	case 6:
		return "ERROR_KIND_ALREADY_EXISTS"
	case 7:
		return "ERROR_KIND_CONFLICT"
	case 8:
		return "ERROR_KIND_RATE_LIMITED"
	case 9:
		return "ERROR_KIND_RESOURCE_EXHAUSTED"
	case 10:
		return "ERROR_KIND_TIMEOUT"
	case 11:
		return "ERROR_KIND_CANCELED"
	case 12:
		return "ERROR_KIND_UNAVAILABLE"
	case 13:
		return "ERROR_KIND_INVALID_RESPONSE"
	case 14:
		return "ERROR_KIND_INTERNAL"
	case 15:
		return "ERROR_KIND_FAILED_PRECONDITION"
	default:
		return "UNKNOWN"
	}
}

type CreateOptions struct {
	Name            *string              `json:"name,omitempty" validate:"omitnil"`
	Source          *SandboxSource       `json:"source,omitempty" validate:"omitnil"`
	Runtime         *RuntimeConfig       `json:"runtime,omitempty" validate:"omitnil"`
	Isolation       *IsolationConfig     `json:"isolation,omitempty" validate:"omitnil"`
	Resources       *Resources           `json:"resources,omitempty" validate:"omitnil"`
	Placement       *Placement           `json:"placement,omitempty" validate:"omitnil"`
	Environment     map[string]string    `json:"environment" validate:""`
	Labels          map[string]string    `json:"labels" validate:""`
	Network         *NetworkConfig       `json:"network,omitempty" validate:"omitnil"`
	Security        *SecurityConfig      `json:"security,omitempty" validate:"omitnil"`
	Lifetime        *LifetimePolicy      `json:"lifetime,omitempty" validate:"omitnil"`
	Provisioning    *ProvisioningOptions `json:"creation,omitempty" validate:"omitnil"`
	Readiness       *ReadinessProbe      `json:"readiness,omitempty" validate:"omitnil"`
	Observability   *ObservabilityConfig `json:"observability,omitempty" validate:"omitnil"`
	ProviderOptions map[string]any       `json:"provider_options,omitempty" validate:"omitnil"`
}

func (x *CreateOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}
func (x *CreateOptions) GetSource() *SandboxSource {
	if x != nil {
		return x.Source
	}
	var zero *SandboxSource
	return zero
}
func (x *CreateOptions) GetRuntime() *RuntimeConfig {
	if x != nil {
		return x.Runtime
	}
	var zero *RuntimeConfig
	return zero
}
func (x *CreateOptions) GetIsolation() *IsolationConfig {
	if x != nil {
		return x.Isolation
	}
	var zero *IsolationConfig
	return zero
}
func (x *CreateOptions) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	var zero *Resources
	return zero
}
func (x *CreateOptions) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	var zero *Placement
	return zero
}
func (x *CreateOptions) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	var zero map[string]string
	return zero
}
func (x *CreateOptions) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	var zero map[string]string
	return zero
}
func (x *CreateOptions) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	var zero *NetworkConfig
	return zero
}
func (x *CreateOptions) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	var zero *SecurityConfig
	return zero
}
func (x *CreateOptions) GetLifetime() *LifetimePolicy {
	if x != nil {
		return x.Lifetime
	}
	var zero *LifetimePolicy
	return zero
}
func (x *CreateOptions) GetProvisioning() *ProvisioningOptions {
	if x != nil {
		return x.Provisioning
	}
	var zero *ProvisioningOptions
	return zero
}
func (x *CreateOptions) GetReadiness() *ReadinessProbe {
	if x != nil {
		return x.Readiness
	}
	var zero *ReadinessProbe
	return zero
}
func (x *CreateOptions) GetObservability() *ObservabilityConfig {
	if x != nil {
		return x.Observability
	}
	var zero *ObservabilityConfig
	return zero
}
func (x *CreateOptions) GetProviderOptions() map[string]any {
	if x != nil {
		return x.ProviderOptions
	}
	var zero map[string]any
	return zero
}

type SandboxSource struct {
	ProviderDefault *ProviderDefaultSource `json:"provider_default,omitempty" validate:"omitnil"`
	Image           *ImageSource           `json:"image,omitempty" validate:"omitnil"`
	Snapshot        *SnapshotSource        `json:"snapshot,omitempty" validate:"omitnil"`
	WarmPool        *WarmPoolSource        `json:"warm_pool,omitempty" validate:"omitnil"`
}

func (x *SandboxSource) GetProviderDefault() *ProviderDefaultSource {
	if x != nil {
		return x.ProviderDefault
	}
	var zero *ProviderDefaultSource
	return zero
}
func (x *SandboxSource) GetImage() *ImageSource {
	if x != nil {
		return x.Image
	}
	var zero *ImageSource
	return zero
}
func (x *SandboxSource) GetSnapshot() *SnapshotSource {
	if x != nil {
		return x.Snapshot
	}
	var zero *SnapshotSource
	return zero
}
func (x *SandboxSource) GetWarmPool() *WarmPoolSource {
	if x != nil {
		return x.WarmPool
	}
	var zero *WarmPoolSource
	return zero
}

type ProviderDefaultSource struct {
}
type ImageSource struct {
	Reference string `json:"reference,omitempty" validate:"nonblank"`
}

func (x *ImageSource) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}

type SnapshotSource struct {
	Reference    string       `json:"reference,omitempty" validate:"nonblank"`
	Kind         SnapshotKind `json:"kind,omitempty" validate:""`
	ProviderKind *string      `json:"provider_kind,omitempty" validate:"omitnil"`
}

func (x *SnapshotSource) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}
func (x *SnapshotSource) GetKind() SnapshotKind {
	if x != nil {
		return x.Kind
	}
	var zero SnapshotKind
	return zero
}
func (x *SnapshotSource) GetProviderKind() string {
	if x != nil && x.ProviderKind != nil {
		return *x.ProviderKind
	}
	var zero string
	return zero
}

type WarmPoolSource struct {
	Reference string `json:"reference,omitempty" validate:"nonblank"`
}

func (x *WarmPoolSource) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}

type RuntimeConfig struct {
	Language         *string  `json:"language,omitempty" validate:"omitnil,nonblank"`
	Version          *string  `json:"version,omitempty" validate:"omitnil,nonblank"`
	User             *string  `json:"user,omitempty" validate:"omitnil,nonblank"`
	WorkingDirectory *string  `json:"working_directory,omitempty" validate:"omitnil,nonblank"`
	Entrypoint       []string `json:"entrypoint" validate:"dive,nonblank"`
	PTY              *bool    `json:"pty,omitempty" validate:"omitnil"`
}

func (x *RuntimeConfig) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	var zero string
	return zero
}
func (x *RuntimeConfig) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	var zero string
	return zero
}
func (x *RuntimeConfig) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	var zero string
	return zero
}
func (x *RuntimeConfig) GetWorkingDirectory() string {
	if x != nil && x.WorkingDirectory != nil {
		return *x.WorkingDirectory
	}
	var zero string
	return zero
}
func (x *RuntimeConfig) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	var zero []string
	return zero
}
func (x *RuntimeConfig) GetPTY() bool {
	if x != nil && x.PTY != nil {
		return *x.PTY
	}
	var zero bool
	return zero
}

type IsolationConfig struct {
	Kind                 IsolationKind `json:"kind,omitempty" validate:""`
	ProviderKind         *string       `json:"provider_kind,omitempty" validate:"omitnil"`
	NestedVirtualization *bool         `json:"nested_virtualization,omitempty" validate:"omitnil"`
}

func (x *IsolationConfig) GetKind() IsolationKind {
	if x != nil {
		return x.Kind
	}
	var zero IsolationKind
	return zero
}
func (x *IsolationConfig) GetProviderKind() string {
	if x != nil && x.ProviderKind != nil {
		return *x.ProviderKind
	}
	var zero string
	return zero
}
func (x *IsolationConfig) GetNestedVirtualization() bool {
	if x != nil && x.NestedVirtualization != nil {
		return *x.NestedVirtualization
	}
	var zero bool
	return zero
}

type Resources struct {
	CPUCores       *float64 `json:"cpu_cores,omitempty" validate:"omitnil,finite,gt=0"`
	CPULimitCores  *float64 `json:"cpu_limit_cores,omitempty" validate:"omitnil,finite,gte=0"`
	MemoryMiB      *uint64  `json:"memory_mib,omitempty" validate:"omitnil,gt=0"`
	MemoryLimitMiB *uint64  `json:"memory_limit_mib,omitempty" validate:"omitnil"`
	DiskMiB        *uint64  `json:"disk_mib,omitempty" validate:"omitnil,gt=0"`
}

func (x *Resources) GetCPUCores() float64 {
	if x != nil && x.CPUCores != nil {
		return *x.CPUCores
	}
	var zero float64
	return zero
}
func (x *Resources) GetCPULimitCores() float64 {
	if x != nil && x.CPULimitCores != nil {
		return *x.CPULimitCores
	}
	var zero float64
	return zero
}
func (x *Resources) GetMemoryMiB() uint64 {
	if x != nil && x.MemoryMiB != nil {
		return *x.MemoryMiB
	}
	var zero uint64
	return zero
}
func (x *Resources) GetMemoryLimitMiB() uint64 {
	if x != nil && x.MemoryLimitMiB != nil {
		return *x.MemoryLimitMiB
	}
	var zero uint64
	return zero
}
func (x *Resources) GetDiskMiB() uint64 {
	if x != nil && x.DiskMiB != nil {
		return *x.DiskMiB
	}
	var zero uint64
	return zero
}

type Placement struct {
	Cloud   *string  `json:"cloud,omitempty" validate:"omitnil"`
	Regions []string `json:"regions" validate:"dive,nonblank"`
	Target  *string  `json:"target,omitempty" validate:"omitnil"`
}

func (x *Placement) GetCloud() string {
	if x != nil && x.Cloud != nil {
		return *x.Cloud
	}
	var zero string
	return zero
}
func (x *Placement) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	var zero []string
	return zero
}
func (x *Placement) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	var zero string
	return zero
}

type StringAllowlist struct {
	Entries []string `json:"entries" validate:""`
}

func (x *StringAllowlist) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	var zero []string
	return zero
}

type NetworkConfig struct {
	Egress           EgressMode       `json:"egress,omitempty" validate:""`
	OutboundCIDRs    *StringAllowlist `json:"outbound_cidrs,omitempty" validate:"omitnil"`
	OutboundDomains  *StringAllowlist `json:"outbound_domains,omitempty" validate:"omitnil"`
	InboundCIDRs     *StringAllowlist `json:"inbound_cidrs,omitempty" validate:"omitnil"`
	PrivateNetwork   *bool            `json:"private_network,omitempty" validate:"omitnil"`
	LinkedSandbox    *string          `json:"linked_sandbox,omitempty" validate:"omitnil"`
	ProxyReference   *string          `json:"proxy_reference,omitempty" validate:"omitnil"`
	OutboundProxyURL *string          `json:"outbound_proxy_url,omitempty" validate:"omitnil"`
	CustomDomain     *string          `json:"custom_domain,omitempty" validate:"omitnil"`
	Ports            []*PortBinding   `json:"ports" validate:"dive,required"`
}

func (x *NetworkConfig) GetEgress() EgressMode {
	if x != nil {
		return x.Egress
	}
	var zero EgressMode
	return zero
}
func (x *NetworkConfig) GetOutboundCIDRs() *StringAllowlist {
	if x != nil {
		return x.OutboundCIDRs
	}
	var zero *StringAllowlist
	return zero
}
func (x *NetworkConfig) GetOutboundDomains() *StringAllowlist {
	if x != nil {
		return x.OutboundDomains
	}
	var zero *StringAllowlist
	return zero
}
func (x *NetworkConfig) GetInboundCIDRs() *StringAllowlist {
	if x != nil {
		return x.InboundCIDRs
	}
	var zero *StringAllowlist
	return zero
}
func (x *NetworkConfig) GetPrivateNetwork() bool {
	if x != nil && x.PrivateNetwork != nil {
		return *x.PrivateNetwork
	}
	var zero bool
	return zero
}
func (x *NetworkConfig) GetLinkedSandbox() string {
	if x != nil && x.LinkedSandbox != nil {
		return *x.LinkedSandbox
	}
	var zero string
	return zero
}
func (x *NetworkConfig) GetProxyReference() string {
	if x != nil && x.ProxyReference != nil {
		return *x.ProxyReference
	}
	var zero string
	return zero
}
func (x *NetworkConfig) GetOutboundProxyURL() string {
	if x != nil && x.OutboundProxyURL != nil {
		return *x.OutboundProxyURL
	}
	var zero string
	return zero
}
func (x *NetworkConfig) GetCustomDomain() string {
	if x != nil && x.CustomDomain != nil {
		return *x.CustomDomain
	}
	var zero string
	return zero
}
func (x *NetworkConfig) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	var zero []*PortBinding
	return zero
}

type PortBinding struct {
	Port      uint32        `json:"port,omitempty" validate:"gte=1,lte=65535"`
	Transport PortTransport `json:"transport,omitempty" validate:""`
}

func (x *PortBinding) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	var zero uint32
	return zero
}
func (x *PortBinding) GetTransport() PortTransport {
	if x != nil {
		return x.Transport
	}
	var zero PortTransport
	return zero
}

type SecurityConfig struct {
	PublicAccess     *bool              `json:"public_access,omitempty" validate:"omitnil"`
	WorkloadIdentity *bool              `json:"workload_identity,omitempty" validate:"omitnil"`
	Secrets          []*SecretReference `json:"secrets" validate:"dive,required"`
}

func (x *SecurityConfig) GetPublicAccess() bool {
	if x != nil && x.PublicAccess != nil {
		return *x.PublicAccess
	}
	var zero bool
	return zero
}
func (x *SecurityConfig) GetWorkloadIdentity() bool {
	if x != nil && x.WorkloadIdentity != nil {
		return *x.WorkloadIdentity
	}
	var zero bool
	return zero
}
func (x *SecurityConfig) GetSecrets() []*SecretReference {
	if x != nil {
		return x.Secrets
	}
	var zero []*SecretReference
	return zero
}

type SecretReference struct {
	Reference           string          `json:"reference,omitempty" validate:"nonblank"`
	EnvironmentVariable *string         `json:"environment_variable,omitempty" validate:"omitnil,nonblank"`
	Injection           SecretInjection `json:"injection,omitempty" validate:""`
}

func (x *SecretReference) GetReference() string {
	if x != nil {
		return x.Reference
	}
	var zero string
	return zero
}
func (x *SecretReference) GetEnvironmentVariable() string {
	if x != nil && x.EnvironmentVariable != nil {
		return *x.EnvironmentVariable
	}
	var zero string
	return zero
}
func (x *SecretReference) GetInjection() SecretInjection {
	if x != nil {
		return x.Injection
	}
	var zero SecretInjection
	return zero
}

type LifetimePolicy struct {
	MaximumLifetime *time.Duration   `json:"maximum_lifetime,omitempty" validate:"omitnil,gte=0"`
	Ephemeral       *bool            `json:"ephemeral,omitempty" validate:"omitnil"`
	IdleTerminate   *AutomaticAction `json:"idle_terminate,omitempty" validate:"omitnil"`
	IdleStop        *AutomaticAction `json:"idle_stop,omitempty" validate:"omitnil"`
	IdlePause       *AutomaticAction `json:"idle_pause,omitempty" validate:"omitnil"`
	StoppedArchive  *AutomaticAction `json:"stopped_archive,omitempty" validate:"omitnil"`
	StoppedDelete   *AutomaticAction `json:"stopped_delete,omitempty" validate:"omitnil"`
}

func (x *LifetimePolicy) GetMaximumLifetime() *time.Duration {
	if x != nil {
		return x.MaximumLifetime
	}
	var zero *time.Duration
	return zero
}
func (x *LifetimePolicy) GetEphemeral() bool {
	if x != nil && x.Ephemeral != nil {
		return *x.Ephemeral
	}
	var zero bool
	return zero
}
func (x *LifetimePolicy) GetIdleTerminate() *AutomaticAction {
	if x != nil {
		return x.IdleTerminate
	}
	var zero *AutomaticAction
	return zero
}
func (x *LifetimePolicy) GetIdleStop() *AutomaticAction {
	if x != nil {
		return x.IdleStop
	}
	var zero *AutomaticAction
	return zero
}
func (x *LifetimePolicy) GetIdlePause() *AutomaticAction {
	if x != nil {
		return x.IdlePause
	}
	var zero *AutomaticAction
	return zero
}
func (x *LifetimePolicy) GetStoppedArchive() *AutomaticAction {
	if x != nil {
		return x.StoppedArchive
	}
	var zero *AutomaticAction
	return zero
}
func (x *LifetimePolicy) GetStoppedDelete() *AutomaticAction {
	if x != nil {
		return x.StoppedDelete
	}
	var zero *AutomaticAction
	return zero
}

type AutomaticAction struct {
	Mode  PolicyMode     `json:"mode,omitempty" validate:"gte=0,lte=2"`
	After *time.Duration `json:"after,omitempty" validate:"omitnil,gte=0"`
}

func (x *AutomaticAction) GetMode() PolicyMode {
	if x != nil {
		return x.Mode
	}
	var zero PolicyMode
	return zero
}
func (x *AutomaticAction) GetAfter() *time.Duration {
	if x != nil {
		return x.After
	}
	var zero *time.Duration
	return zero
}

type ProvisioningOptions struct {
	Timeout      *time.Duration `json:"timeout,omitempty" validate:"omitnil,gte=0"`
	QueueTimeout *time.Duration `json:"queue_timeout,omitempty" validate:"omitnil,gte=0"`
	WaitFor      WaitCondition  `json:"wait_for,omitempty" validate:""`
}

func (x *ProvisioningOptions) GetTimeout() *time.Duration {
	if x != nil {
		return x.Timeout
	}
	var zero *time.Duration
	return zero
}
func (x *ProvisioningOptions) GetQueueTimeout() *time.Duration {
	if x != nil {
		return x.QueueTimeout
	}
	var zero *time.Duration
	return zero
}
func (x *ProvisioningOptions) GetWaitFor() WaitCondition {
	if x != nil {
		return x.WaitFor
	}
	var zero WaitCondition
	return zero
}

type ReadinessProbe struct {
	TCPPort *uint32       `json:"tcp_port,omitempty" validate:"omitnil,gte=1,lte=65535"`
	Command *CommandProbe `json:"command,omitempty" validate:"omitnil"`
}

func (x *ReadinessProbe) GetTCPPort() uint32 {
	if x != nil && x.TCPPort != nil {
		return *x.TCPPort
	}
	var zero uint32
	return zero
}
func (x *ReadinessProbe) GetCommand() *CommandProbe {
	if x != nil {
		return x.Command
	}
	var zero *CommandProbe
	return zero
}

type CommandProbe struct {
	Argv []string `json:"argv" validate:"min=1"`
}

func (x *CommandProbe) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	var zero []string
	return zero
}

type ObservabilityConfig struct {
	Verbose           *bool   `json:"verbose,omitempty" validate:"omitnil"`
	TelemetryEndpoint *string `json:"telemetry_endpoint,omitempty" validate:"omitnil,nonblank"`
}

func (x *ObservabilityConfig) GetVerbose() bool {
	if x != nil && x.Verbose != nil {
		return *x.Verbose
	}
	var zero bool
	return zero
}
func (x *ObservabilityConfig) GetTelemetryEndpoint() string {
	if x != nil && x.TelemetryEndpoint != nil {
		return *x.TelemetryEndpoint
	}
	var zero string
	return zero
}

type CreateResult struct {
	Sandbox *SandboxInfo `json:"sandbox,omitempty" validate:"omitnil"`
}

func (x *CreateResult) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	var zero *SandboxInfo
	return zero
}

type SandboxInfo struct {
	ID               string                 `json:"id,omitempty" validate:""`
	Provider         string                 `json:"provider,omitempty" validate:""`
	Name             *string                `json:"name,omitempty" validate:"omitnil"`
	ProviderState    *string                `json:"provider_state,omitempty" validate:"omitnil"`
	Region           *string                `json:"region,omitempty" validate:"omitnil"`
	Isolation        *IsolationConfig       `json:"isolation,omitempty" validate:"omitnil"`
	Resources        *Resources             `json:"resources,omitempty" validate:"omitnil"`
	Labels           map[string]string      `json:"labels" validate:""`
	CreatedAt        *time.Time             `json:"created_at,omitempty" validate:"omitnil"`
	ProviderMetadata map[string]any         `json:"provider_metadata,omitempty" validate:"omitnil"`
	Origins          map[string]ValueOrigin `json:"origins" validate:""`
}

func (x *SandboxInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	var zero string
	return zero
}
func (x *SandboxInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	var zero string
	return zero
}
func (x *SandboxInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}
func (x *SandboxInfo) GetProviderState() string {
	if x != nil && x.ProviderState != nil {
		return *x.ProviderState
	}
	var zero string
	return zero
}
func (x *SandboxInfo) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	var zero string
	return zero
}
func (x *SandboxInfo) GetIsolation() *IsolationConfig {
	if x != nil {
		return x.Isolation
	}
	var zero *IsolationConfig
	return zero
}
func (x *SandboxInfo) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	var zero *Resources
	return zero
}
func (x *SandboxInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	var zero map[string]string
	return zero
}
func (x *SandboxInfo) GetCreatedAt() *time.Time {
	if x != nil {
		return x.CreatedAt
	}
	var zero *time.Time
	return zero
}
func (x *SandboxInfo) GetProviderMetadata() map[string]any {
	if x != nil {
		return x.ProviderMetadata
	}
	var zero map[string]any
	return zero
}
func (x *SandboxInfo) GetOrigins() map[string]ValueOrigin {
	if x != nil {
		return x.Origins
	}
	var zero map[string]ValueOrigin
	return zero
}

type ErrorInfo struct {
	Kind           ErrorKind `json:"kind,omitempty" validate:""`
	Provider       string    `json:"provider,omitempty" validate:""`
	Operation      string    `json:"operation,omitempty" validate:""`
	Field          string    `json:"field,omitempty" validate:""`
	Message        string    `json:"message,omitempty" validate:""`
	StatusCode     *uint32   `json:"status_code,omitempty" validate:"omitnil"`
	ProviderCode   *string   `json:"provider_code,omitempty" validate:"omitnil"`
	ProviderSource *string   `json:"provider_source,omitempty" validate:"omitnil"`
}

func (x *ErrorInfo) GetKind() ErrorKind {
	if x != nil {
		return x.Kind
	}
	var zero ErrorKind
	return zero
}
func (x *ErrorInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	var zero string
	return zero
}
func (x *ErrorInfo) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	var zero string
	return zero
}
func (x *ErrorInfo) GetField() string {
	if x != nil {
		return x.Field
	}
	var zero string
	return zero
}
func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	var zero string
	return zero
}
func (x *ErrorInfo) GetStatusCode() uint32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	var zero uint32
	return zero
}
func (x *ErrorInfo) GetProviderCode() string {
	if x != nil && x.ProviderCode != nil {
		return *x.ProviderCode
	}
	var zero string
	return zero
}
func (x *ErrorInfo) GetProviderSource() string {
	if x != nil && x.ProviderSource != nil {
		return *x.ProviderSource
	}
	var zero string
	return zero
}

type MetadataValue struct {
	Boolean         *bool          `json:"boolean,omitempty" validate:"omitnil"`
	Text            *string        `json:"text,omitempty" validate:"omitnil"`
	SignedInteger   *int64         `json:"signed_integer,omitempty" validate:"omitnil"`
	UnsignedInteger *uint64        `json:"unsigned_integer,omitempty" validate:"omitnil"`
	Number          *float64       `json:"number,omitempty" validate:"omitnil"`
	Binary          *[]byte        `json:"binary,omitempty" validate:"omitnil"`
	List            *MetadataList  `json:"list,omitempty" validate:"omitnil"`
	Object          map[string]any `json:"object,omitempty" validate:"omitnil"`
}

func (x *MetadataValue) GetBoolean() bool {
	if x != nil && x.Boolean != nil {
		return *x.Boolean
	}
	var zero bool
	return zero
}
func (x *MetadataValue) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	var zero string
	return zero
}
func (x *MetadataValue) GetSignedInteger() int64 {
	if x != nil && x.SignedInteger != nil {
		return *x.SignedInteger
	}
	var zero int64
	return zero
}
func (x *MetadataValue) GetUnsignedInteger() uint64 {
	if x != nil && x.UnsignedInteger != nil {
		return *x.UnsignedInteger
	}
	var zero uint64
	return zero
}
func (x *MetadataValue) GetNumber() float64 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	var zero float64
	return zero
}
func (x *MetadataValue) GetBinary() []byte {
	if x != nil && x.Binary != nil {
		return *x.Binary
	}
	var zero []byte
	return zero
}
func (x *MetadataValue) GetList() *MetadataList {
	if x != nil {
		return x.List
	}
	var zero *MetadataList
	return zero
}
func (x *MetadataValue) GetObject() map[string]any {
	if x != nil {
		return x.Object
	}
	var zero map[string]any
	return zero
}

type MetadataList struct {
	Values []*MetadataValue `json:"values" validate:"dive,required"`
}

func (x *MetadataList) GetValues() []*MetadataValue {
	if x != nil {
		return x.Values
	}
	var zero []*MetadataValue
	return zero
}

type MetadataObject struct {
	Values map[string]*MetadataValue `json:"values" validate:""`
}

func (x *MetadataObject) GetValues() map[string]*MetadataValue {
	if x != nil {
		return x.Values
	}
	var zero map[string]*MetadataValue
	return zero
}

// Value marks an optional scalar as explicitly supplied, including zero/false.
func Value[T any](value T) *T { return &value }
